apiVersion: v1
data:
  properties.yaml: "---\nversion: 0.1.0\nspec:\n  units: []\nproperties: []\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: nifi-operator
    app.kubernetes.io/name: nifi-operator
    app.kubernetes.io/version: 26.7.0
    stackable.tech/vendor: Stackable
  name: nifi-operator-configmap
