---
# Source: ab-runtime-operator/templates/cloud.abinitio.com_cooperatingsystemruntimeresourcesrequests.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    meta.helm.sh/chart: ab-runtime-operator-2.5.0
    ab-installation-tag: "release-4-4/b1576027-m1576027"
  name: cooperatingsystemruntimeresourcesrequests.cloud.abinitio.com
spec:
  group: cloud.abinitio.com
  names:
    kind: CoOperatingSystemRuntimeResourcesRequest
    listKind: CoOperatingSystemRuntimeResourcesRequestList
    plural: cooperatingsystemruntimeresourcesrequests
    singular: cooperatingsystemruntimeresourcesrequest
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          resourceRequests:
            items:
              properties:
                agents:
                  items:
                    properties:
                      agentName:
                        type: string
                      argList:
                        items:
                          type: string
                        type: array
                      generation:
                        type: string
                      muxName:
                        type: string
                      resources:
                        properties:
                          claims:
                            items:
                              properties:
                                name:
                                  type: string
                              required:
                              - name
                              type: object
                            type: array
                            x-kubernetes-list-map-keys:
                            - name
                            x-kubernetes-list-type: map
                          limits:
                            additionalProperties:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            type: object
                          requests:
                            additionalProperties:
                              anyOf:
                              - type: integer
                              - type: string
                              pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                              x-kubernetes-int-or-string: true
                            type: object
                        type: object
                    type: object
                  type: array
                deleteAgentPvcWithAgent:
                  type: boolean
                jobName:
                  type: string
                jobTag:
                  type: string
              required:
              - jobName
              type: object
            type: array
        type: object
    served: true
    storage: true
