---
catalog_templates:
  - template_name: v4.16.yaml
    channels: [alpha]
    replaces: amd-gpu-operator.1.5.0
  - template_name: v4.17.yaml
    channels: [alpha]
    replaces: amd-gpu-operator.1.5.0
  - template_name: v4.18.yaml
    channels: [alpha]
    replaces: amd-gpu-operator.1.5.0
  - template_name: v4.19.yaml
    channels: [alpha]
    replaces: amd-gpu-operator.1.5.0
  - template_name: v4.20.yaml
    channels: [alpha]
    replaces: amd-gpu-operator.1.5.0
  - template_name: v4.21.yaml
    channels: [alpha]
    replaces: amd-gpu-operator.1.5.0
  - template_name: v4.22.yaml
    channels: [alpha]
    replaces: amd-gpu-operator.1.5.0
