---
catalog_templates:
  - template_name: v4.16.yaml
    channels: [stable]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.16.yaml
    channels: [candidate, fast]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.17.yaml
    channels: [stable]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.17.yaml
    channels: [candidate, fast]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.18.yaml
    channels: [stable]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.18.yaml
    channels: [candidate, fast]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.19.yaml
    channels: [stable]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.19.yaml
    channels: [candidate, fast]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.20.yaml
    channels: [stable]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.20.yaml
    channels: [candidate, fast]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.21.yaml
    channels: [stable]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.21.yaml
    channels: [candidate, fast]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.22.yaml
    channels: [stable]
    replaces: rbln-npu-operator.v0.4.3
  - template_name: v4.22.yaml
    channels: [candidate, fast]
    replaces: rbln-npu-operator.v0.4.3
