---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apps.cloudcasa.io/v1alpha1",
          "kind": "Cloudcasa",
          "metadata": {
            "name": "cloudcasa-sample"
          },
          "spec": {
            "clusterID": "",
            "image": {
              "repository": "cloudcasaAgent.azurecr.io/catalogicsoftware/amds-kagent",
              "tag": "3.1.0-prod"
            },
            "imagePullSecret": null,
            "server": {
              "address": "agent.cloudcasa.io:443",
              "skipTLSVerification": false
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: Storage
    containerImage: registry.connect.redhat.com/catalogicsoftware/cloudcasa-operator@sha256:e6d09e04727f8dc2b76387d33adbccef7df6c6d6be241073ea5d3532de47b78e
    createdAt: "2026-03-26T00:00:00Z"
    description: CloudCasa is a backup, restore, disaster recovery, and migration service for Red Hat OpenShift, OpenShift Virtualization, and all Kubernetes platforms.
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "true"
    features.operators.openshift.io/tls-profiles: "true"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.operatorframework.io/builder: operator-sdk-v1.8.0-ocp
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
  name: cloudcasa-operator.v4.1.1
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Cloudcasa
      name: cloudcasas.apps.cloudcasa.io
      version: v1alpha1
      description: Agent for backup and restore services.
      displayName: CloudCasa
      specDescriptors:
      - description: Cluster ID for registering the User Kubernetes to CloudCasa
        displayName: Cluster ID
        path: clusterID
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:password
      resources:
      - kind: Deployment
        version: apps/v1
        name: ""
      - kind: Pod
        version: v1
        name: ""
      - kind: Service
        version: v1
        name: ""
  description: CloudCasa is a backup, restore, disaster recovery, and migration service for Red Hat OpenShift, OpenShift Virtualization, and all Kubernetes platforms.
  displayName: CloudCasa Operator
  icon:
    - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI0LjAuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCAzMDAgMzAwIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCAzMDAgMzAwOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+CjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+Cgkuc3Qwe2ZpbGw6dXJsKCNTVkdJRF8xXyk7fQoJLnN0MXtmaWxsOnVybCgjU1ZHSURfMl8pO30KPC9zdHlsZT4KPGc+CgkKCQk8bGluZWFyR3JhZGllbnQgaWQ9IlNWR0lEXzFfIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjgwLjE0NDUiIHkxPSI3MS4xODAyIiB4Mj0iMjUxLjk3OTUiIHkyPSIyMzcuMTE5NCIgZ3JhZGllbnRUcmFuc2Zvcm09Im1hdHJpeCgxIDAgMCAtMSAwIDMwNCkiPgoJCTxzdG9wICBvZmZzZXQ9IjAiIHN0eWxlPSJzdG9wLWNvbG9yOiM4NDNENzIiLz4KCQk8c3RvcCAgb2Zmc2V0PSIxIiBzdHlsZT0ic3RvcC1jb2xvcjojREIyMzhCIi8+Cgk8L2xpbmVhckdyYWRpZW50PgoJPHBhdGggY2xhc3M9InN0MCIgZD0iTTI0Myw1OC44Yy0yMC43LTE3LjUtNDcuNi0yOC4xLTc3LTI4LjFDMTAwLjIsMzAuNyw0Ni43LDg0LjEsNDYuNywxNTBzNTMuNCwxMTkuNCwxMTkuMywxMTkuNAoJCWMyOS4zLDAsNTYuMy0xMC42LDc3LTI4LjFsMTAuMi05LjhsLTI0LjktOS42Yy0xNi4zLDEzLjktMzcuNiwyMi4xLTYwLjcsMjIuMWMtNTEuOCwwLTk0LTQyLTk0LTk0YzAtNTEuOCw0Mi05NCw5NC05NAoJCWMyMy4xLDAsNDQuMiw4LjQsNjAuNywyMi4xbDI0LjktOS42bDAsMEwyNDMsNTguOHoiLz4KCQoJCTxsaW5lYXJHcmFkaWVudCBpZD0iU1ZHSURfMl8iIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIiB4MT0iMTA5LjIyNzEiIHkxPSI5Ni45NTcxIiB4Mj0iMjI3LjM3NTIiIHkyPSIyMTEuMDUxMyIgZ3JhZGllbnRUcmFuc2Zvcm09Im1hdHJpeCgxIDAgMCAtMSAwIDMwNCkiPgoJCTxzdG9wICBvZmZzZXQ9IjAiIHN0eWxlPSJzdG9wLWNvbG9yOiM4NDNENzIiLz4KCQk8c3RvcCAgb2Zmc2V0PSIxIiBzdHlsZT0ic3RvcC1jb2xvcjojREIyMzhCIi8+Cgk8L2xpbmVhckdyYWRpZW50PgoJPHBhdGggY2xhc3M9InN0MSIgZD0iTTE2OC4zLDIzMi4yYzQ1LjIsMCw4Mi4yLTM2LjgsODIuMi04Mi4yYzAtNDUuMi0zNi44LTgyLjItODIuMi04Mi4yYy0yMi43LDAtNDMuMiw5LjItNTguMSwyNC4xbDE1LjcsMTUuNwoJCWMxMC44LTEwLjksMjUuOS0xNy43LDQyLjQtMTcuN2MzMy4yLDAsNjAuMSwyNi45LDYwLjEsNjAuMXMtMjYuOSw2MC4xLTYwLjEsNjAuMWMtMTYuNSwwLTMxLjUtNi42LTQyLjQtMTcuN2wtMTUuNywxNS43CgkJQzEyNS4xLDIyMi45LDE0NS42LDIzMi4yLDE2OC4zLDIzMi4yeiIvPgo8L2c+Cjwvc3ZnPgo=
      mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - apps.cloudcasa.io
          resources:
          - cloudcasas
          - cloudcasas/status
          - cloudcasas/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - serviceaccounts
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          verbs:
          - bind
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          verbs:
          - bind
          - create
          - delete
          - escalate
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: cloudcasa-operator-controller-manager
      deployments:
      - name: cloudcasa-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:d9198020b835dff4838aff140e85baa6d672b8ad439baae6d0e12ba86b8ae239
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources:
                  limits:
                    cpu: 100m
                    memory: 128Mi
                  requests:
                    cpu: 100m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --leader-election-id=cloudcasa-operator
                - --max-concurrent-reconciles=5
                image: registry.connect.redhat.com/catalogicsoftware/cloudcasa-operator@sha256:e6d09e04727f8dc2b76387d33adbccef7df6c6d6be241073ea5d3532de47b78e
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 512Mi
                  requests:
                    cpu: 100m
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: cloudcasa-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: cloudcasa-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - storage
  links:
  - name: CloudCasa Operator
    url: https://cloudcasa.io
  maturity: alpha
  provider:
    name: CloudCasa
    url: https://cloudcasa.io
  version: 4.1.1
  replaces: cloudcasa-operator.v4.1.0
  minKubeVersion: 1.24.0
  maintainers:
  - email: support@cloudcasa.io
    name: CatalogicSoftware
  relatedImages:
    - image: registry.connect.redhat.com/catalogicsoftware/cloudcasa-operator@sha256:e6d09e04727f8dc2b76387d33adbccef7df6c6d6be241073ea5d3532de47b78e
      name: manager
    - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:d9198020b835dff4838aff140e85baa6d672b8ad439baae6d0e12ba86b8ae239
      name: kube-rbac-proxy
