apiVersion: v1
kind: Service
metadata:
  annotations:
    containerImage: harness/gitops-agent-controller@sha256:b2ef26452d95e5fe390cf5653a0a1d706a6c18c8b4a532c6066df29ea86d162c
    createdAt: "2026-04-28T17:19:35Z"
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitops-operator
    control-plane: harness-gitops-operator
  name: harness-gitops-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: harness-gitops-operator
status:
  loadBalancer: {}
