---
catalog_templates:
  - template_name: v4.13.yaml
    channels: [alpha]
    replaces: dxoperator-v2.v2.0.86
  - template_name: v4.14.yaml
    channels: [alpha]
    replaces: dxoperator-v2.v2.0.86
  - template_name: v4.15.yaml
    channels: [alpha]
    replaces: dxoperator-v2.v2.0.86
  - template_name: v4.16.yaml
    channels: [alpha]
    replaces: dxoperator-v2.v2.0.86
  - template_name: v4.17.yaml
    channels: [alpha]
    replaces: dxoperator-v2.v2.0.86
  - template_name: v4.18.yaml
    channels: [alpha]
    replaces: dxoperator-v2.v2.0.86
  - template_name: v4.19.yaml
    channels: [alpha]
    replaces: dxoperator-v2.v2.0.86
  - template_name: v4.20.yaml
    channels: [alpha]
    replaces: dxoperator-v2.v2.0.86
  - template_name: v4.21.yaml
    channels: [alpha]
    replaces: dxoperator-v2.v2.0.86
  - template_name: v4.22.yaml
    channels: [alpha]
    replaces: dxoperator-v2.v2.0.86
