---
catalog_templates:
  - template_name: v4.18.yaml
    channels: ['1.24']
  - template_name: v4.18.yaml
    channels: [stable]
    replaces: habana-ai-operator.v1.23.0-695

  - template_name: v4.19.yaml
    channels: ['1.24']
  - template_name: v4.19.yaml
    channels: [stable]
    replaces: habana-ai-operator.v1.23.0-695

  - template_name: v4.20.yaml
    channels: ['1.24']
  - template_name: v4.20.yaml
    channels: [stable]
    replaces: habana-ai-operator.v1.23.0-695

  - template_name: v4.21.yaml
    channels: ['1.24']
  - template_name: v4.21.yaml
    channels: [stable]
    replaces: habana-ai-operator.v1.23.0-695
