apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cas
    control-plane: sas-cas-olm-operator
  name: sas-cas-olm-operator-metrics-service
spec:
  ports:
  - name: metrics
    port: 8443
    protocol: TCP
    targetPort: 8383
  selector:
    app.kubernetes.io/name: cas
    control-plane: sas-cas-operator
status:
  loadBalancer: {}
