apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "viya.sas.com/v1alpha1",
          "kind": "CASDeployment",
          "metadata": {
            "name": "casdeployment-sample"
          },
          "spec": {
            "controllerTemplate": {
              "spec": {
                "containers": [
                  {
                    "image": "sas-cas-server:latest",
                    "name": "sas-cas-server"
                  },
                  {
                    "image": "sas-backup-agent:latest",
                    "name": "sas-backup-agent"
                  }
                ]
              }
            },
            "shutdown": false,
            "workerTemplate": {},
            "workers": 0
          }
        }
      ]
    capabilities: Basic Install
    categories: Big Data
    certified: "false"
    containerImage: quay.io/dzanter/operator:3.69.22@sha256:ea7f421077e775fa29ba10f78a2d4ce6e0a9a070dcc7527bf915952921ae3845
    createdAt: "2026-07-23T20:53:58Z"
    features.operators.openshift.io/cnf: 'false'
    features.operators.openshift.io/cni: 'false'
    features.operators.openshift.io/csi: 'false'
    features.operators.openshift.io/disconnected: 'false'
    features.operators.openshift.io/fips-compliant: 'false'
    features.operators.openshift.io/proxy-aware: 'false'
    features.operators.openshift.io/tls-profiles: 'false'
    features.operators.openshift.io/token-auth-aws: 'false'
    features.operators.openshift.io/token-auth-azure: 'false'
    features.operators.openshift.io/token-auth-gcp: 'false'
    operators.operatorframework.io/builder: operator-sdk-v1.42.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    support: SAS Institute
  name: sas-cas-operator.v1.2.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Custom Resource for the CASDeployment, which defines the desired state of a CAS deployment
        displayName: CASDeployment
        kind: CASDeployment
        name: casdeployments.viya.sas.com
        resources:
          - kind: Pod
            name: ""
            version: v1
          - kind: Deployment
            name: ""
            version: apps/v1
        specDescriptors:
          - description: Pod Template for the CAS Controller
            displayName: Controller Template
            path: controllerTemplate
          - description: Pod Template for the CAS Workers
            displayName: Worker Template
            path: workerTemplate
          - description: Number of CAS Worker replicas
            displayName: Workers
            path: workers
          - description: A toggle to either shutdown or start the CAS deployment
            displayName: Shutdown
            path: shutdown
        statusDescriptors:
          - description: Conditions
            displayName: Conditions
            path: conditions
          - description: The CAS Controller Failed
            displayName: Controller Failed
            path: controllerFailed
          - description: The CAS Controller Started
            displayName: Controller Started
            path: controllerStarted
        version: v1alpha1
  description: |
    Kubernetes Operator for the SAS Cloud Analytics Server. Manages the CAS controller Pod as well as any defined CAS worker Pods.
  displayName: SAS CAS Operator
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAHW1JREFUeNrs3d11E8m2AOAe1n0/nghGjmDsx/OEHAEQAXYEQASGCIAI7InAJgKLp/toEwEigvFJ4J7bBVuDMNiWu6ta1dL3raXlwxmQW6Xu2rXrt2kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAOvymCPL44+X/Ttofkzv+yvWXd/++UlKAALKdQWKn/bHXvqbpjxEwph3eKgWS6/b1Mf73VRtc5koYEEA2K2CkAPEkfk4K/roUQGYRVM7bgHLtGwAEkPEFjsMIGk/XeBnn7etDG0hOfSOAAFJ/tvGyfb1oXzsVXVrKRFIQea+bCxBA6gscb9vX4QguNwWSNwIJIIDIOAQSQAAZWfB4GlnHZMQfI3VtpW6t125jQAAZJus4adY7OJ5bmgZ8ZI0JMLRHWxQ8pu2Pyw0LHklal3LZfr6XbmdABpI/eKTK9e0WfNTzyEasIQEEkAzBI3VZHW7Rd5q6sp4ZYAcEkO6BI413nDXdthoZu5SBHBgXAQSQbsHjovk2PrCtBBFAABE8BJHffnu0c/M7/e9//2/mK761vFJZ7SivH8pk0vw4df+6LRMNLAHkhwByKXiMM4jEAz6Nh/xxVIAP+S4XFWT6rF/i51VbSWzUpIKlYJrKarEr9M3KcRWLXaHTz/9E+Y26vNqymUbZ/Bnl8VMgvedZWZTJp+bbBqdXgsyWBJARDJjPblRuTVuxz+74PIubf1E5/BkPRJeK4qDG2VntA5+mVZfe7fgqyv5jWxmcjzRgTJthdoUeVXlFo2P5Hir57H5IPwWUDQwglU7VvVrcdHcFig6ftUuFkq7hoJKHPgXBF/HgD72NTAqiqVL8q/YunQiuz5v1rl1alNebtrzmFZXNYZTNdA2/PpXD+/Z1umnZ7VYGkFgkeFHJ5aSb6690cw01lTYyleeRfd1VIb9Z59Yn0b1w3NQzM24WFWNVgSQqx+Omvq12Ujm9WlcLPDKx2vavO60tuAogD2+Nf67ghppHBX265vK4r/I5yJkNPaCb4aSpd0r1WivGEQSOm95FpXmtbL43zlK5bFtGsgkB5KyCFD8FjneVlcttD1wKdPtDjYe0D/7ruI4xSJXi4BnaCALsbQ2mZ6WD7sjKZpAyqcmo98KKrqt1nxq4W1vwSFIm1L52U8s6gtzCJLoBinc3tK+LEQWP5Li95rPoKhmyZX3ZjG/Ba7qPLmKcplTZPB1Z2aQyuYzvVAYyggDyeU0pbZVZxx3l9KtW3G6pMZoYJD9rxrtd/tdZa6W7I9pyejtEMB/AQe5xpKiET0ZcJmmA/UgGUm+l+HpNFVSqdA/GEjwiG5nHDKzlay6SGUTwuGjGfdbKXrSui2Ui7XufbEjwSM7iexc8vjuMBoIMpMLgsa6B82rXUzyg7JYfzqxZSPRXXzbjO+HxNmnOf/apzxE8Nq2bIy242xc8fnLUlsupDKSy6L6GSup07MEjspH0OY4KZSFnGxQ8kmnuVmT7fi+bzdwdei8mTPTNXk82rFxOcmZnMpA8reihxz7SgPRG9WcuZSJZspAN6s//lSx9/FGRXG5wj0ZqXO12GTuK7sLLZtxdn0WzMwEkT8X3NFq6g335bQW7kV9+jCM1fRcXxgLBkgs5F/sTLfYo+ucjLFU405orgAEqyMU+TklqEHy58d8fx8+H7i/2UJ2mQhdugNxVNotymRQOXmuZIl7a/4zwmp8MGTxS63NTm4spcMT+YX0dZ37Y0/Toj823MYiVs6No4e/FPZJzemnqnjns2Zf9MnMF9c82OV2yoyiraVSgOcsqrRJ//cBrmWQOHv+UTfPAzSGjMTSNeyhnoH3RvvfGLTQcYwby3wHT8f1NP9kvpvhedx3byZh9pIf9fa7N+6LFfxgVWo6Ke95e227Ha0m//3Ome3KxB1O2+zKub1FWOcawnj3ke8w4qeC0ybityNKebYeZinrjspBRBZCBu6/SsbDnDfc9ZH13AkiV4lHJXV8zroZ/1uU6M1WQxbcPiaB7kiEjWXkNRKbgOot7aF6oXCZNntXwnRshtRrbLKzHA/2ec8Fj5QqnT2WTuhp2S28ZHq2+NIbRt4J5soYyuo7A9ap090d6//b1rPlxvVAXD6locwSrg5KbGab3juncr3q+1aTkyn0BJO+N2atFLDwUf/jTA38wVJ9w7E+033wfTO3isMPiwpR57PS4Fw+GPpMjBavmW3dQn4py1c/cZ0xz0NXe7e96l6FueLJJFcDYAsgQ86nfjH2tx0gywqOhBxTj9z1rftwbrHQj5nmP37W2jfmiYr4a4Fnt2ii8WsdWITGRos/vlYGsQ2ycWNp8TFuUjDgjPF3XGRzR1fFsiKAZfeddGz01nFPSp8tmskL59Hmm36yrUCKIdM0KdzZpYeGYpvFOBvgd2W7K2G7lsPn5qM1Ugc0i05mP/P7p+p18WOdFp4q5fYjPO7YGp4X+bnPjHll7QybKadbxc6xyb3StSK8rOGr3KMplp+M9tBFbvo+pC6t0ALnu0aq4GTxSxZRmlrz9xcM3icDyebGQb4x6tqJmFXyErq3rh3zurl187ytaL/BXwffeGev9E9/Pacd//uemZCCPGhbOc4x9tEEhBY1V94Q6zrSQbx12ej58664A5l1bgQ8Inl2D7GlF33PJyvqPjv/uUyVl877SxrAAkvFmW1XvbpXIKB66ovYw9qXaFjWl7l1b16sGzy4B5Lym1coRaEtdz6gr0h6NkKkAMrySN9t133UfMcjfdbHayUCTBGpQ0wBi19b1vd9Vjy6+j4L+qMy2+cPrwsr3gPRd6XwW24psvJidVEMLsmTFuLPGe3HTPa7oWj51fAY2YibWmALIvOB792r1tRX/Xoa0dCeCyM4WVAA1ZVulKuy9yq5nk57p6ZDn1hf6DBvxnI9pGu+XiiuRXBXi4kCdZyP4Pvr0i6ds7bSSLKTUVv07Ha9nmxax9nmm01jj6wrun1kz0nOVti2A1FoZ5m5NPE0zub68+/ermgssdf+0rcCu/zxtdfEytobY5Nb1zKNV7LlL26OfltwDi80KINt0o7xsg8inOH629u9k0vHfvm0rgKsKVluXCrCnTV3TcWvIsHNm/l+7fNt76GDLsraqGANpvh6sVGMldhJjKzXrW24X6aAmj2G9Sn4/GRoPe3EPTXxTAkjJ1sqdMsx+KhWALiofVM8x5fQkHWda0aAo34NH+k6OC/+aHEHkUkNEALkvS7gumIVMel7brNC17VQeRHLtR5QGRD+ng58Ekqq8bcov9vuQ6TlJDZGLnhs0ssEZSNEsJINSW0vvxYNcnZ77Af2qEjiOQPJWt8R6M484aXKIVv1pxvdKwSMFka8ZicaIAHJTqVW6vVstkYWU2mL6sOKNF3NvtrezlJGkiuClYDJo8EhBI20EOsi5FZkbIcuNrpO4h1Jm8lQwEUCSUls4Z9lnqw0ir5tyM2+Oa9wzKwZCZ4Wzr1QRLDITlUH+oLEXZft3VLxDl29qeJWYSbU4UiFlU39HF9fLTTqPY+33ztguuK1EL5v8+ymlg6R2M13f13GLpsyeT1+POG2vtaquvMgQLgeueK4icKWsdGYq58rf1U7cmynr/rPpfqbFvUEhzqJf9brS3z0esCiul+6fjZ1OLoD8XEG/bMqMCezmOuApgsjnQg/mdVxrVRVmdH2sc2v6q3gtAsp8qx/sb0F9EsHij/i5N2CQf1AAiWu+aNa7zc1yg0RA2dAAMonKObdXOY+zjTUcF4Ue2Kv2Wveru5l+e3TSDDPwulJWeaNC2MiAsnRs7l5kFDtNHXuNdQkgO5HJTiopXgFl0wJIVM4lWirZurGWrrNkq/y0vd6j6m6ouoLIzYCSxtA+VnAcateyXQSHFCweD5xRFA8g8RlLNrxyBJQPEVDsmjziAJJmiJwVeOuD3KvSY/ZUqb7drFnTFgSRhcXxxR9qDiYRMJ5GsJg24zqAqVMAWcqqzpq6zo65rUHy1zYHk9HuItlWzJ8LPFCztkI+KHCtJSvUZ30PwypU+aXP+7apf9vqRTB5X0NFEJVnChrPK69AiwWQpeB50gw0nbindN+k6eyn2zaZY8wHSpVYczEtdDLgq6bcIsgq98yKzQT3m/p3pF1M9bxc10rmWLiXFr6l/v/PEXi3eqppqojbVzrW4FlT7kjdXJanm59s07ql0QaQ2Kl2XuCt3xa41uuCD0K1B1Glgev2lTK6o2Ycuymn4HExVCCJwPE6gsbJtgeNW+6hlB2msckxbP2/aIxszbY8Yz/StkQWsldi1XdMET4oVA6pxXNRcSWQUvvdEQaSIps83ggcx0293XzzaPjM1nz/pGzkVQSS05HUTYtteZ42G2zUASSykBI393GJbqFYAFhsz6wYa6m5NbkcSMYwEyqtObrMuXI5MpvLygPH1/s0fVc1TTKIjDbdO79H47H2xsjizJKzTc1GHm3AZyh1ct9JiW6hCHql0vHDWGhZe7fEafRv7zZlx4dyZXdZtguPrOOiqW821WIiwddWfjrmN8awar1/UkbyOhojB5GV1DxO8rTZ0HNLNuIs33QEbLQWcztvK/xnha75rCk3w+Sg0kOy7qpcJ833Kau1pv1HXSvWiqY2z+P1MX5e3Tf7rOMK8V6zsDqWccoUnzff18rU5utWRJs07XdTAkjJFazvSpxPvo17Zj2wMphGRfC4qWNldecgsobgsRwkktSYuO5acY0lgNy45uU1NHsVBZT0vexvynTfjQggUSFPm3IDyUclziePbVlKbUJ4FUFkM27UbwFlbymgrKtP+UGtyMLB47r5vv9X+jkv0bodYwC5JaBMlwLKOhsls5idKIBUFkTSDVtq1fd+iRZ9DNZfFrrmKrc7yVQhTG5kKJMBf33q9tlf4RpT4Mg9sWGxaG2w7TQ2IYCskOUOvS1M9eWzdQEkKuQS270vWnv7uXbsvXHNJSqaotlTxQHlyUAZyp0VQOYt7tO99775ttJ5voay3cgA8ovPmeqN5a1jStsd+yafjzawLhndgr3CM7PeRlfZRospnl9nd7Wv3+M+eNeUm53z4p6pmTmm6aZrfxMVzett36J+gHvoKso5dS+le6j0dPPjsZfZxgWQyBCeFXr7vVKZQgzUl7hZd5r1ntOxrsrgPC0+WwomswLlenhH9nHY8/1T99R+VGgOyxr+/rlemm6e7qH0fOYO4Idjn9q7iRnI4nzyUn3/T2PacAlHTZk1EdMxrA8pHExSq/IgcyB5UahleRprMWQc9QSTd4V2Uxj1SvVHm/qlR7fQaaG3f1nifPLCe2Yd17hf1sAVwWL2S64yntxcpR7dWn3ujfNYbU2d91CqU9IEilxdzs8FkHqDyFFTbh+fk0LbncwLZU+pYnurCvhhg74c2d40Y4uy1HdP/ozkVaaGyN6Ytzl5tAXf97Om3FYZFyUGqON8jxLjIYeFtqsfZSXQfOvS6ntvPL7nzw9xZLxjdA2RgxxBRACpNwu5jlbd2LZSL3XNxx79n4LIvMfbTO7JSFZ15dztUd5DqQHSd6eK0TbqtiEDWeyCO6qZWRH4SmwUOZWF/BREXvX8/r+KroiuGen7iotp4k658x46bfp1lf9rrJ/9t236omMmUqlxgFJ7ZlV3dG/Hw5bmNc8qaj9T53JuP9dvS+XSdTud32vtvmo/1387/LNbFxLG1NVJh3KeVXz/9NlRYrRbm2xVAIkKueTeRNlXfRdcpb7bdVV97gqlkgqgT+MiTbm96rF1yTymiNZYLl2D4l0BJE00OOsaqDewETLaALIVXVjLYmbWmM4nTwN1xkLK63NPLMbAumaK84rL5UmB9+x0P+c82KuQ2bY9NFsXQMJBwYc268ysGAspMSOrz3TTLpXtnxscQMb8u0veJ7nVPt31iwCyHVlIyQV7JWZmfShxnT0WQ3Ypt6pbjz3HH/o2Rv5TY5lE99WkwFt3La+pRFkAqSWIFD2fvMk4bhHrQkro2j3RpcU82cQjPSP4zDf0MTmurLweNwggFQWRxTnQRVL/zPtPzQpcY9cWXddUvdp9f9bcv/5nheXxtHCLv0sjZDrmVduZy0IAqSSIpD1tTgu9fdpK/WnFN9lOxzUhXa/lRcW3wmSN30tVlWJU0qW3velabjVvCto1Q/pPM1JbH0DCq6bszKwcFUSpm+zBAaTHfPxJTHWtUdfuvHmO76CylvVJU37x4KeujZCKs5CuWeysGSkBpPlnUD3Hnja3tS5ztJpK3WRdW01dA+5xbRVAXE/XTPFTpst4WklZvB7oWs57PE/VTUGPhlHX+3rejJQAMkwQeVLxR+/aavqraxbS1Lcr8MseD/8sU5Bf+7beUQnmqpz/uCeLnfeoOF923A2hpK7lNh/zJAwB5McgkmNjtJyV9BB2Onax9ZkZdhgt3Rpajns9Hv7rG915fRof0xi4Xlc5pKCec8eDSeF76KyWhYVRdpOO//y8GTEB5Ocgctp8O4d6mzz4QYxWU59xo9SVdbLmBz997oseb3F+o0z6jqOdDF0ppu679nXWrGdwus8GkqnRc7HuIBJZW5+y+2vMFYcA8usg8rqpb2BrUvC9d9ZQASwykYt1rA9Z2uNpJ/PDf97zezgZqjyi8kv7N60l84lGyKxneV2uK5vNkLXNMzQ6BJBKpZXq80zvleMmKVmp7HWsAE4zlNF0UQkMMbgeLe63GYLH7JbZaB8zfBeXJbuzUvBMgTsqv1JlPl3x7+XI9lM2eznUuEiU32WGrG30PR0CyO1ZSM7tTnKkqbXuJZXjIVjMrPmcKvcS3RLpPaPL7HOTp7vmts99nqk8ziI7m2b6/ClwvowdYy+aAbYFWSUIRhDOke1/7Y6MQHJYojES73sR5df3Hp1HA2zUtm4794eKhYBnPd4iBaDdCEh9rqPEuSD/VIbRbdf1wbps8k8UmEdlnKbJXj001Y8glF6Po7LMWXZ3br8dlUzOCjp99g93ZD2/DBjx+dN1PGnWM5Hj68zGm99ddNHtxZGwfc9RufN7ioxwFvfQ9QPun+XyS4233BnhkQCyPUGkz1kRvc8Iid19P5fMInoGkD6H6Tw0qMxXaImW7ApLldD+XVMvC1aIq5ZD7uwi3b+HPSvy5exq72YQjm7FIQbyr1boVSidnY32/I+b/kd4uF/a7qStxP/s8BCdZjpgalpz+cRhSqlLp/QCr0mz/uNVX903bz9lCW15zAp+b0OWQ2q5H/XcQWCVcngTf690prTuqb+LrvGNYAxk9SBy1Dxsz6w38W9yeF57+cTpc+cbfhucPqDbYROmgqfW+sFS1lPy/kkV61FTZiFvTZ7VenSxADJMEHlzz02eWp4HfbqElkX3VfGUOtP7lDztsYbgsXKDIMYq3o09eCxVdvPSvzDGSkrtBlGDo5rPdRdAhgkiKTDsRmX5Lirf0wgs++1/T8Ej503yYixlE5XNwQYGkQcFj6XyeDXSspjdCB7NUJ9jg4PIRgya32QQvWKxxUgaPC+6PqINeD/dBzFTJmU+k2h9zlbdsydmsKQps0834Gt4F4Gg2wP2rSxyTPtca7CMKblnGX/PfTPZFrsEjP38j69jHjczj3i+nsbnS8/V+Ri7tmQgdTse4AGa36zwltZLpOzncfz8HDNlVspE2tezZtzjAIsHv9feaCPKyq6jlXx0y+c4HzIriExkf+TZbAoa+8vBY2nrmPR8PVl6vv6uZX+4hzALq97sI7XAhprWuOwsso6j5ud+77S4bWfV7pw0sB6zkYY4XyKn86hMs1SY6X3acjiIsp1WWtEdrZBhpnI5HDCIpOvZj4r1eET3T7pv3rTX/6sxsMX07pvP12Ibm3/1bbTIQEiG2vL841Lr6DAquJQ9PI+K/zgqvuP4/w8fsjo6tb7a125z/+SDWirS1PeffaZMZGUpiLyqqBzmETgOVuyeXMu1xwy/3WYcs/xO07X+KniknQCiIfWr5+txBJWXtewyLICMN/t4PWBLdfmhTCn16dLK4b+WKr1ppOJXTYdpxUuVQI2B5DwCx0HpWTJRsew35Y5RXjVwpPUsuw8Z2I2gupbWcQpw0S16sOayuy3jeBeB467MdfF8zX/xfC1W5qf/Npqxw9EEkDSdNdPRsLV/zj7nUzy4Ivny7t830+gvS39+HttyvF16aD80HbujohX+un39Hq2tdbYoF2e/7EbGMRvqF0dleBQBdcjKcBYZx+4t3SurXPtpfHc5Kt0uv3+2VHZvmvWe5rfo6vw9dTutkMWlRuGnW56vq6Xg/rgZiTGNgVxHQR81GyrWfFwM/ADcV+Ekk6Vxjz8yVaKpIjpdOk62xJ5VN++f9HlSl915DafAxTWkVd6vogyeFGh9nuf+zOm7a6953nQb20rfw/um5xqZ+Cwpq30dXT7TKL+SmfvV0j0069DNOb9RXrNotF3dGPeYNyMxqmm8bQWbbtiPmbYHqe2zrWO65+5yBhKzrJ6mFmq0jD7Gg/45Wnuni//dtQV77w354yZ2/1oqj1UrhtnSQ/gl/jyqY0NjjGkvgvVes9rWJYs9nq7ic18NkVXF9N4ndwT/xTWl18fFBoqFr2lvqdz+jEp6lTJcvt4m7v/rXGUZsxtTY+xg6flKz9RlNIzT7/i7GdGakbEFkGlUsvtx/Kzg0aM7Iy16vHGDT+Jmfh+V96dobaZK4nk8TE+j22fTt5yAEoEtPV+vonGweL4OIwNfNJ72x/J8jWoQPVZ4p8BxEWMFgkd3b27pFkg394torV0vzbhadDUdCB7wcDE5JWUab+N5msfzdb2UdY9qr6wxzsJ6H4V/ERnJmIPH3pqCx+y27VYidd5vvo85LQb55tEyulIVQOcgsni+krOl52sWmf2onq9RbmXSVrzLBxgdjXFMJA6qKnmk6F1y79cFbKGxrgNZnrFw0lbGZ2Oa4hvrPM7WFDxmggewtRlIVMKpAl6e8vh1kVPN2Uh0WZ00691Yb/fG2g+ArQsgt+1Um1rXb2pqZce1pm0M1r2fz5tc55QAjHo797ZiPowW/a+kAPK+rTDP13h9i8Dxoln/ttRXbVnsu+UBAeR7JX2zK+umefNtNe5fQ60dia6qtG7isKnjPIPUvbev6woQQH5u5a86FXYRTL5uRdBWqNcZr2PafN+KYlJZMT1bZyYGCCA1B5Gup5ddRVD51HzfCuL6tkwlgtXy1hqLrSZqXtRo3AMQQAoFkU122gaPI8UAlLAx54FE1vDKVyp4ADKQrpnIYXP7zCzBA0AAuTOIrHObEMEDEEBGHkS2cUzEgDkggGQKIuvaKn1oafbYkam6gACSP5Ck7ZJfbujHu4rgYZt1QAApFESmTbcznGv2rg0cZp4Ba/FoWz5obK6Y9oJ6twEfJ2Ub+4IHIAMZPhuZRDYyHdmlp7GONFD+zq0LCCDrDSQpgByPIJCkwJGO8n2Xc/8uAAGkfyBJs7TSlutp/UhN037nEThOBQ5AAKk7kOxEEEnBZF1Tf1OgSNNxP5iWCwgg4w4maYv2aeHMJA2Kz9rXR0EDEEA2L6BMIpCkn48joDw0S7luvm8h/yWCxpXuKUAA2d7gMr0vwxAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAy/l+AAQDex81veNr8YAAAAABJRU5ErkJggg==
      mediatype: image/png
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
                - pods
                - secrets
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - extensions
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - projectcontour.io
              resources:
                - httpproxies
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - route.openshift.io
                - route.openshift.io/custom-host
              resources:
                - routes
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - viya.sas.com
                - viya.sas.com/finalizers
                - viya.sas.com/status
              resources:
                - casdeployments
              verbs:
                - get
                - list
                - patch
                - update
                - watch
          serviceAccountName: sas-cas-operator
      deployments:
        - label:
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/name: cas
            control-plane: sas-cas-operator
          name: sas-cas-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app.kubernetes.io/name: cas
                control-plane: sas-cas-operator
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  app.kubernetes.io/name: cas
                  control-plane: sas-cas-operator
              spec:
                containers:
                  - args:
                      - --metrics-addr=:8383
                      - --leader-elect
                    command:
                      - /opt/sas/viya/home/bin/cas
                    image: quay.io/dzanter/operator:3.69.22@sha256:ea7f421077e775fa29ba10f78a2d4ce6e0a9a070dcc7527bf915952921ae3845
                    name: sas-cas-operator
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 10m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                securityContext:
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
                serviceAccountName: sas-cas-operator
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: sas-cas-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - sas
    - cas
    - operator
    - viya
    - analytics
    - cloud
  links:
    - name: SAS Cloud Analytic Services Concepts
      url: https://go.documentation.sas.com/doc/hi/sasadmincdc/v_075/calserverscas/n05000viyaservers000000admin.htm
  maintainers:
    - email: david.zanter@sas.com
      name: David Zanter
  maturity: stable
  minKubeVersion: 1.32.0
  provider:
    name: SAS Institute
  selector:
    matchLabels:
      app.kubernetes.io/name: cas
      control-plane: sas-cas-operator
  version: 1.2.3
  relatedImages:
    - name: sas-cas-operator
      image: quay.io/dzanter/operator:3.69.22@sha256:ea7f421077e775fa29ba10f78a2d4ce6e0a9a070dcc7527bf915952921ae3845
