---
catalog_templates:
  - template_name: v4.12.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v4.13.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v4.14.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v4.15.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v4.16.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v4.17.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v4.18.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v4.19.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v4.20.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v4.21.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v4.22.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v4.23.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v5.0.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
  - template_name: v5.1.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.47
