apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: axera-operator
  name: axera-operator-axera-editor-role
rules:
- apiGroups:
  - platform.axerasecurity.com
  resources:
  - axeras
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.axerasecurity.com
  resources:
  - axeras/status
  verbs:
  - get
