{
 "title": "Airlock Microgateway License",
 "description": "Overview on Airlock Microgateway License attributes and usage.",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "license_id",
    "label": "License ID",
    "query": {
     "query": "label_values(microgateway_license_info,id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "License Status",
   "type": "stat",
   "description": "Aggregated status of the Airlock Microgateway licenses selected in the dashboard filter.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(microgateway_license_valid * on (service,instance) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"})",
     "legendFormat": "License Status"
    }
   ]
  },
  {
   "title": "License Expiry Date",
   "type": "stat",
   "description": "Next upcoming expiry date over all Airlock Microgateway licenses selected in the dashboard filter.",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "time: L" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(microgateway_license_expiry_timestamp_seconds * on (service, namespace) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"})*1000",
     "legendFormat": "Expiry Date (MM/DD/YYYY)"
    }
   ]
  },
  {
   "title": "Licensed Requests",
   "type": "stat",
   "description": "Sum of the number licensed requests over all Airlock Microgateway licenses selected in the dashboard filter.",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(topk(1, (microgateway_license_max_rq_count_per_month > 0) * on (service, namespace) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"}) by (id))",
     "legendFormat": "Licensed Requests"
    }
   ]
  },
  {
   "title": "Requests over 30 days (estimated)",
   "type": "stat",
   "description": "Estimated number of requests over 30 days, based on the request count over the last 7 days across all Microgateway instances using any of the licenses selected in the dashboard filter.",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((label_replace(increase(microgateway_license_http_rq_total[7d]), \"namespace\", \"$1\", \"managed_by\", \"(.+)\")) * on(namespace) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"}))/7*30",
     "legendFormat": "Estimated Requests"
    }
   ]
  },
  {
   "title": "Processed Requests per week",
   "type": "timeseries",
   "description": "Number of requests per week processed by Airlock Microgateway.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((label_replace(avg_over_time(increase(microgateway_license_http_rq_total[7d])[2m:15s]), \"namespace\", \"$1\", \"managed_by\", \"(.+)\")) * on(namespace) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"})",
     "legendFormat": "# Requests per week"
    }
   ]
  },
  {
   "title": "Estimated usage over 30 days by Operator Namespace",
   "type": "table",
   "description": "Estimated number of requests over 30 days based on the last 7 days per operator namespace for the Airlock Microgateway licenses selected in the dashboard filter.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(sum by (namespace, id) ((label_replace(increase(microgateway_license_http_rq_total[7d]), \"namespace\", \"$1\", \"managed_by\", \"(.+)\")) * on(namespace) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"}))/7*30",
     "legendFormat": "__auto"
    },
    {
     "expr": "(min by(namespace) (microgateway_build_info{container=\"manager\"})) * on (namespace) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "License Overview",
   "type": "table",
   "description": "Metadata for the Airlock Microgateway licenses selected in the dashboard filter.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "min by (id) (microgateway_license_valid * on (service, namespace) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(1,microgateway_license_max_rq_count_per_month * on (service, namespace) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"})by (id)",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (id) (microgateway_license_is_premium * on (service, namespace) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "min by (id) (microgateway_license_expiry_timestamp_seconds * on (service, namespace) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"})*1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (id) ((label_replace(increase(microgateway_license_http_rq_total[7d]), \"namespace\", \"$1\", \"managed_by\", \"(.+)\")) * on(namespace) group_left(id) microgateway_license_info{id=~\"${license_id.regex}\"}))/7*30",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}