{
 "title": "Airlock Microgateway Threats Block - Metrics",
 "description": "Metrics on threats blocked by Airlock Microgateway.\n\nDashboard can be filtered by namespaces as well as block types.",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource Prometheus", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "DS_LOKI", "query": "loki" },
   {
    "name": "gateway_kind",
    "label": "Gateway Kind",
    "query": {
     "query": "label_values(microgateway_build_info,gateway_kind)"
    }
   },
   {
    "name": "operator",
    "label": "Operator",
    "query": {
     "query": "label_values(microgateway_build_info,managed_by)"
    }
   },
   {
    "name": "namespace",
    "label": "Gateway Namespace",
    "query": {
     "query": "label_values(microgateway_build_info{managed_by=~\"$operator\"},namespace)"
    }
   },
   {
    "name": "gateway_name",
    "label": "Gateway Name",
    "query": {
     "query": "label_values(microgateway_build_info{managed_by=~\"$operator\", namespace=~\"$namespace\", gateway_kind=~\"$gateway_kind\"},gateway)"
    }
   },
   {
    "name": "sidecar_application_port",
    "label": "Sidecar Application Port",
    "query": {
     "query": "label_values(envoy_cluster_bind_errors{managed_by=~\"$operator\", namespace=~\"$namespace\", gateway_kind=~\"SidecarGateway\", gateway=~\"$gateway_name\"},upstream)"
    }
   },
   {
    "name": "gateway_httproute",
    "label": "Gateway HTTPRoute",
    "query": {
     "query": "label_values(envoy_cluster_bind_errors{managed_by=~\"$operator\", namespace=~\"$namespace\", gateway_kind=\"Gateway\", gateway=~\"$gateway_name\"},upstream)"
    }
   },
   {
    "name": "blockType",
    "label": "Block Type",
    "query": {
     "query": "label_values(microgateway_http_downstream_rq_threats_blocked_total,block_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Airlock Microgateway Threats Block - Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Requests",
   "type": "stat",
   "description": "Total number of requests processed by Airlock Microgateway.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\",namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[$__range]))+\nsum(increase(microgateway_http_downstream_rq_threats_blocked_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[$__range]) or on() vector(0)))",
     "legendFormat": "Processed Requests"
    }
   ]
  },
  {
   "title": "% Blocked Requests",
   "type": "stat",
   "description": "Ratio of blocked requests vs. processed requests by Airlock Microgateway.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${blockType:regex}\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[$__range]) or on() vector(0))\n/ \n(\nsum(increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[$__range]))\n+\nsum(increase(microgateway_http_downstream_rq_threats_blocked_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[$__range]) or on() vector(0))\n)",
     "legendFormat": "Blocked Requests (%)"
    }
   ]
  },
  {
   "title": "Requests vs. % Blocks",
   "type": "timeseries",
   "description": "Requests per second processed by Airlock Microgateway along with the corresponding block rate.",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[1m]))\n+\nsum(rate(microgateway_http_downstream_rq_threats_blocked_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[1m]) or on() vector(0))",
     "legendFormat": "Requests per second"
    },
    {
     "expr": "sum(rate(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${blockType:regex}\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[1m]) or on() vector(0))\n/\n(\nsum(rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[1m]))\n+\nsum(rate(microgateway_http_downstream_rq_threats_blocked_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[1m]) or on() vector(0))\n)",
     "legendFormat": "% Blocks"
    }
   ]
  },
  {
   "title": "Block Type",
   "type": "barchart",
   "description": "Blocked threats by block type.",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (block_type) (increase(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${blockType:regex}\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Subtype",
   "type": "barchart",
   "description": "Blocked threats by block subtype, which are subsets of the various block types.",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (block_subtype) (increase(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${blockType:regex}\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`(^upstream_.+|^httproute/.+)`,upstream=~`(${gateway_httproute:regex}|${sidecar_application_port:regex})`}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}