apiVersion: v1
data:
  status: |
    {
      "lastTransmission": "",
      "test": "true",
      "sokVersion": "3.2.0"
    }
kind: ConfigMap
metadata:
  labels:
    name: splunk-operator
  name: splunk-operator-manager-telemetry
