apiVersion: v1
data:
  0_linbit_sds_images.yaml: |
    base: drbd.io
    components:
      drbd-module-loader:
        digest: sha256:9ba017132b9711fdfc6022ef7b35ba62265ec1d3e4f03dce0ac0aed9a05d6d51
        image: drbd9-rhel9
        match:
        - digest: sha256:b9779792595466cd60a4cd65bfbee9ebe40cd49b012d1cd3f65dfc867c669c56
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux 8\.
          precompiled: true
        - digest: sha256:9ba017132b9711fdfc6022ef7b35ba62265ec1d3e4f03dce0ac0aed9a05d6d51
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux 9\.
          precompiled: true
        - digest: sha256:e2790bff533b787d13e0ffe4e867484322ef5105502d887184ce9aade24da6e1
          image: drbd9-rhel10
          osImage: Red Hat Enterprise Linux 10\.
          precompiled: true
        - digest: sha256:9ba017132b9711fdfc6022ef7b35ba62265ec1d3e4f03dce0ac0aed9a05d6d51
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux CoreOS 9|(41[3-9])
          precompiled: true
        - digest: sha256:b9779792595466cd60a4cd65bfbee9ebe40cd49b012d1cd3f65dfc867c669c56
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux CoreOS
          precompiled: true
        - digest: sha256:b9779792595466cd60a4cd65bfbee9ebe40cd49b012d1cd3f65dfc867c669c56
          image: drbd9-rhel8
          osImage: AlmaLinux 8
          precompiled: true
        - digest: sha256:9ba017132b9711fdfc6022ef7b35ba62265ec1d3e4f03dce0ac0aed9a05d6d51
          image: drbd9-rhel9
          osImage: AlmaLinux 9
          precompiled: true
        - digest: sha256:e2790bff533b787d13e0ffe4e867484322ef5105502d887184ce9aade24da6e1
          image: drbd9-rhel10
          osImage: AlmaLinux 10
          precompiled: true
        - digest: sha256:b9779792595466cd60a4cd65bfbee9ebe40cd49b012d1cd3f65dfc867c669c56
          image: drbd9-rhel8
          osImage: Oracle Linux Server 8\.
          precompiled: true
        - digest: sha256:9ba017132b9711fdfc6022ef7b35ba62265ec1d3e4f03dce0ac0aed9a05d6d51
          image: drbd9-rhel9
          osImage: Oracle Linux Server 9\.
          precompiled: true
        - digest: sha256:e2790bff533b787d13e0ffe4e867484322ef5105502d887184ce9aade24da6e1
          image: drbd9-rhel10
          osImage: Oracle Linux Server 10\.
          precompiled: true
        - digest: sha256:b9779792595466cd60a4cd65bfbee9ebe40cd49b012d1cd3f65dfc867c669c56
          image: drbd9-rhel8
          osImage: Rocky Linux 8
          precompiled: true
        - digest: sha256:9ba017132b9711fdfc6022ef7b35ba62265ec1d3e4f03dce0ac0aed9a05d6d51
          image: drbd9-rhel9
          osImage: Rocky Linux 9
          precompiled: true
        - digest: sha256:e2790bff533b787d13e0ffe4e867484322ef5105502d887184ce9aade24da6e1
          image: drbd9-rhel10
          osImage: Rocky Linux 10
          precompiled: true
        tag: v9.3.3
      drbd-reactor:
        digest: sha256:e7bcf410acdd31f98d2c88e425042f2ef7750d52142d2bdc2f07b9b57ee836ed
        image: drbd-reactor
        tag: v1.12.0
      drbd-shutdown-guard:
        digest: sha256:16793f5aa10b46b198806c9198216fbd1aaec31269c28adea7e526dd17ff6f57
        image: drbd-shutdown-guard
        tag: v1.1.2
      ha-controller:
        digest: sha256:6373cac061702973b5460f742678adeb81167e23d774b0c1151252f2893b1c85
        image: linstor-k8s-ha-controller
        tag: v1.3.3
      ktls-utils:
        digest: sha256:3351a6e0fc048fe1544499095cdb8fdd221e832cecfa8a9a01f046c271991138
        image: ktls-utils
        tag: v1.2.1
      linstor-affinity-controller:
        digest: sha256:76f25c6a6cfdb430a1f7459ab91a7af5ca8130b95cfd9a413e5e16966ee06bca
        image: linstor-affinity-controller
        tag: v1.5.0
      linstor-controller:
        digest: sha256:f0f713ec3346de3d1bcfa1894788157ed73d8f335c11955e54ffae63707c2efe
        image: linstor-controller
        tag: v1.34.2
      linstor-csi:
        digest: sha256:8001a6ed5381126133d11a30321a1bb834f47e1ea312863883044e1811577944
        image: linstor-csi
        tag: v1.12.0
      linstor-satellite:
        digest: sha256:3614fb54093f086059515bccf6d9887186fc42d075682ec6a829d4d3f2139513
        image: linstor-satellite
        tag: v1.34.2
      nfs-server:
        digest: sha256:e8ca5799b05805a10c6b3115838de8c0ccc91ffb0e50ef80502601ae8df46a5b
        image: nfs-server
        tag: v1.12.0
  0_redhat_ose_images.yaml: |
    base: registry.redhat.io/openshift4
    components:
      csi-attacher:
        digest: sha256:b78d9153e0b1ae05d8a2ef3ac49debe16a196710ac9a0058e9f234b31a8498ca
        image: ose-csi-external-attacher-rhel9
        tag: latest
      csi-livenessprobe:
        digest: sha256:2d0dc4e6380cab3b5546135bca97b6539ca6b00a51abba8a7dfbf50cd956797c
        image: ose-csi-livenessprobe-rhel9
        tag: latest
      csi-node-driver-registrar:
        digest: sha256:a61ab0fe291ca115a0fd5bd17f973d0792d4bdc9f54c7c6091a5cba9a6e85fba
        image: ose-csi-node-driver-registrar-rhel9
        tag: latest
      csi-provisioner:
        digest: sha256:9e596b1874e6037f87eb08530792d168306e8e5e67db67bff276fb0fe9ab33ae
        image: ose-csi-external-provisioner-rhel9
        tag: latest
      csi-resizer:
        digest: sha256:d6cfd26f5e7fddc8c2d74018cf8fb43e9a20c7694e331953bead76aaa0eab3aa
        image: ose-csi-external-resizer-rhel9
        tag: latest
      csi-snapshotter:
        digest: sha256:c37972da9a278f68a2b4b8c78057e3bc5652a5b81aecaf7bd55aaee259bdee9e
        image: ose-csi-external-snapshotter-rhel9
        tag: latest
  0_sig_storage_images.yaml: |
    base: registry.k8s.io/sig-storage
    components:
      csi-external-health-monitor-controller:
        digest: sha256:430c1f2267152ce6e4547ebbad225a2b399d03e5894f2f39ba233a38e4750a47
        image: csi-external-health-monitor-controller
        tag: v0.18.0
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: linbit-sds
  name: linstor-operator-image-config
