---
catalog_templates:
  - template_name: v4.18.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.48
  - template_name: v4.19.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.48
  - template_name: v4.20.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.48
  - template_name: v4.21.yaml
    channels:
      - lts
      - stable-v6.0
    replaces: zabbix-operator-certified.v6.0.48
