apiVersion: v1
data:
  minkms: |
    image: "quay.io/minio/aistor/minkms:RELEASE.2026-04-09T16-36-52Z"
  minkms-sidecar: |
    image: "quay.io/minio/aistor/minkms-sidecar:RELEASE.2026-04-11T08-18-20Z"
kind: ConfigMap
metadata:
  name: minkms-operator-default
