---
catalog_templates:
  - template_name: v4.18.yaml
    channels:
      - stable-v7.0
    defaultChannel: stable-v7.0
    replaces: zabbix-operator-certified.v6.0.48-1
    skipRange: ">=6.0.0 <7.0.30"
  - template_name: v4.19.yaml
    channels:
      - stable-v7.0
    defaultChannel: stable-v7.0
    replaces: zabbix-operator-certified.v6.0.48-1
    skipRange: ">=6.0.0 <7.0.30"
  - template_name: v4.20.yaml
    channels:
      - stable-v7.0
    defaultChannel: stable-v7.0
    replaces: zabbix-operator-certified.v6.0.48-1
    skipRange: ">=6.0.0 <7.0.30"
  - template_name: v4.21.yaml
    channels:
      - stable-v7.0
    defaultChannel: stable-v7.0
    replaces: zabbix-operator-certified.v6.0.48-1
    skipRange: ">=6.0.0 <7.0.30"
