apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flow-cni-operator
  name: flow-cni-operator-manager-hostnetwork-scc-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:hostnetwork-v2
subjects:
- kind: ServiceAccount
  name: flow-cni-operator-controller-manager
  namespace: flow-cni-operator-system
