apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: strategy-operator
  name: strategy-operator-mstrmanagementservice-viewer-role
rules:
- apiGroups:
  - cloud.microstrategy.com
  resources:
  - mstrmanagementservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.microstrategy.com
  resources:
  - mstrmanagementservices/status
  verbs:
  - get
