{
 "title": "Airlock Microgateway System - Metrics",
 "description": "Metrics on system resources of the Airlock Microgateway.",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "gateway_kind",
    "label": "Gateway Kind",
    "query": {
     "query": "label_values(microgateway_build_info,gateway_kind)"
    }
   },
   {
    "name": "namespace",
    "label": "Gateway Namespace",
    "query": {
     "query": "label_values(microgateway_build_info{gateway_kind=\"$gateway_kind\"},namespace)"
    }
   },
   {
    "name": "gateway_name",
    "label": "Gateway Name",
    "query": {
     "query": "label_values(microgateway_build_info{namespace=~\"$namespace\", gateway_kind=~\"$gateway_kind\"},gateway)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "query_result(max_over_time(microgateway_build_info{container=\"airlock-microgateway-engine\", gateway_kind=\"$gateway_kind\", namespace=\"$namespace\", gateway=\"$gateway_name\"}[$__range]) > 0)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gateway Configuration Status",
   "type": "stat",
   "description": "Aggregated status of the resource conditions of the gateway instance.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "min(microgateway_config_resource_condition{kind=\"${gateway_kind}\", name=\"${gateway_name}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Envoy Server State Summary",
   "type": "stat",
   "description": "Indicator if all Envoy server states of the selected gateway are in state LIVE.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "min(envoy_server_live{gateway_kind=\"${gateway_kind}\", gateway=\"${gateway_name}\", container=\"airlock-microgateway-engine\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }, "repeat": "pod" },
  {
   "title": "Readiness Microgateway Engine",
   "type": "stat",
   "description": "Readiness status of the Airlock Microgateway Engine container.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"airlock-microgateway-engine\",pod=\"${pod}\"}",
     "legendFormat": "Health"
    }
   ]
  },
  {
   "title": "Envoy Server State",
   "type": "stat",
   "description": "State of the Envoy Server",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_server_state{gateway_kind=\"${gateway_kind}\", gateway=\"${gateway_name}\", container=\"airlock-microgateway-engine\", pod=\"${pod}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Microgateway Engine",
   "type": "timeseries",
   "description": "Memory usage over time of the Airlock Microgateway Engine container.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{pod=\"${pod}\",container=\"airlock-microgateway-engine\",resource=\"memory\"}",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=\"${pod}\", container=\"airlock-microgateway-engine\", resource=\"memory\"}",
     "legendFormat": "Request"
    },
    {
     "expr": "container_memory_usage_bytes{pod=\"${pod}\",container=\"airlock-microgateway-engine\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Envoy Server",
   "type": "timeseries",
   "description": "Allocated memory and heap size over time of the Envoy server in the Microgateway Engine container.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "envoy_server_memory_allocated{pod=\"${pod}\", container=\"airlock-microgateway-engine\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "envoy_server_memory_heap_size{pod=\"${pod}\", container=\"airlock-microgateway-engine\"}",
     "legendFormat": "Heap"
    }
   ]
  },
  {
   "title": "CPU Usage Microgateway Engine",
   "type": "timeseries",
   "description": "CPU usage over time of the Airlock Microgateway Engine container.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": " sum(kube_pod_container_resource_limits{pod=\"${pod}\",container=\"airlock-microgateway-engine\",resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": " sum(kube_pod_container_resource_requests{pod=\"${pod}\",container=\"airlock-microgateway-engine\",resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=\"${pod}\",container=\"airlock-microgateway-engine\"}[$__rate_interval])",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Pod Network I/O",
   "type": "timeseries",
   "description": "Pod network I/O over time.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "Received"
    }
   ]
  },
  {
   "title": "Airlock Microgateway Engine Version",
   "type": "stat",
   "description": "Version of the Airlock Microgateway Engine container.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "microgateway_build_info{container=\"airlock-microgateway-engine\",pod=\"${pod}\"}",
     "legendFormat": "Version"
    }
   ]
  }
 ]
}