---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "cluster-services-openshift.cloud.google.com/v1alpha1",
          "kind": "TelemetryConfig",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "google-cloud-cluster-services-telemetry-agent"
            },
            "name": "telemetryconfig-sample"
          },
          "spec": null
        }
      ]
    capabilities: Deep Insights
    containerImage: us-docker.pkg.dev/workload-agent-products/cluster-services-for-openshift-telemetry/controller@sha256:05f5411d942e915c6dd05d629a9d068cc1fc90a8dce8bfe3d8f12e98bad22a28
    createdAt: "2026-07-14T17:03:25Z"
    description: Cluster Services for OpenShift - For deeper Integrations and best
      practices configuration with Google Cloud Products.
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.operatorframework.io/builder: operator-sdk-v1.39.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    support: Google Cloud
  name: google-cloud-cluster-services-for-openshift-telemetry.v0.0.7
  namespace: placeholder
spec:
  relatedImages:
  - name: manager
    image: us-docker.pkg.dev/workload-agent-products/cluster-services-for-openshift-telemetry/controller@sha256:05f5411d942e915c6dd05d629a9d068cc1fc90a8dce8bfe3d8f12e98bad22a28
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TelemetryConfig is the Schema for the telemetryconfigs API
      displayName: Telemetry Config
      kind: TelemetryConfig
      name: telemetryconfigs.cluster-services-openshift.cloud.google.com
      specDescriptors:
      - description: Enabled defines if the telemetry agent should be enabled
        displayName: Enabled
        path: enabled
      - description: The repository of the telemetry agent image to use.
        displayName: Image Repository
        path: imageRepository
      - description: The version of the telemetry agent image to use.
        displayName: Image Version
        path: imageVersion
      - description: |-
          The path of the service account's credentials stored as a secret. This is the credential that
          will be used to authenticate with the Google Cloud Telemetry Manager.
          If not specified, it defaults to "/var/run/secrets/google/service_account.json".
          In the case of Workload Identity Federation (WIF) / Workload Identity, this path points to the WIF config file.
          For example: "/var/run/secrets/cloud.google.com/serviceaccount/file-name"
        displayName: Service Account Credentials Path
        path: serviceAccountCredentialsPath
      - description: |-
          The name of the Kubernetes secret containing the service account's credentials. This is the
          credential that will be used to authenticate with the Google Cloud Telemetry Manager.
          If not specified, it defaults to "google-cloud-cluster-services-telemetry-agent-wif-secret".
          In the case of Workload Identity Federation (WIF) / Workload Identity, this secret is created
          by applying the secret manifests generated by the ccoctl tool from the CredentialsRequest.
        displayName: Service Account Credentials Secret Name
        path: serviceAccountCredentialsSecretName
      - description: The audience of the service account's token used for workload
          identity authentication requests.
        displayName: Service Account Token Audience
        path: serviceAccountTokenAudience
      statusDescriptors:
      - description: |-
          For further information see: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
          Conditions store the status conditions of the Openshift instances
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: |-
    Choose [Cluster Services for OpenShift][productlink] when you need the following:

    * Follow Best Practices: Validate configurations against Google Cloud and Red Hat recommended practices.
    * Improve Reliability: Proactively identify settings that could impact availability and resilience.
    * Strengthen Security: Ensure secure configurations for storage, secrets, and identity.
    * Optimize Total Cost of Ownership (TCO): Get recommendations for cost-effective service usage and configurations.

    ## Guide

    Follow [these][guidelink] steps to install and configure the Telemetry agent.

    ## Support

    For support, please file a support case through [Google Cloud Customer Care][supportlink].

    [productlink]: https://docs.cloud.google.com/compute/docs/containers/cluster-services-for-openshift-overview
    [guidelink]: https://docs.cloud.google.com/workload-manager/docs/evaluate/set-up-operator-for-openshift
    [supportlink]: https://cloud.google.com/support-hub
  displayName: Cluster Services for OpenShift Telemetry
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAADY0lEQVR4AcXVA5QkVxSA4f++6q7GoHdPsmPEtm3btm3btpOD2LZtc22MPdPuqneDORn02l8Zz2JhE2ZBt9suRjB3AB47YWQNVCpRySJOCzi/gfMu0eAr8tprnXOVgJ6wbpAeczGJ4Ln4pgg/ACq9BwIS6Dus43aicptJNN8in33mkceQR09ZrZqc9x2iVwFFIMzGEDVynV9c8anuvP8w8gQYQO+uqKE58Tlht5akBV8gq71HzgEMICD/F8jQSwDpopCumZZAX8ClrOcVylK1BBSWTENxFhyFiN9KUJ/BcCHImRZ9EKgTFBDAvuOEsvvIiy9mZ14CN3oeGdYBYGgaEiEAn0juBtJFt8rbn8UZQNdd9yyGVV+I0fVNmP37Is8jAPopYZxIAzmJ0RmEpAMpxzKt4Fi5ZtLjzAcDQCyyFyIxokCRB7EsOP79fZHPdwJG9iNKr4hCgU0SydwA8y8AoLAcBiQsYEFd+chsG29iBta6QS0zo0o/Oem3S+WRAABKDQiIQY2ioiOZFyIDb0v7SpDPBlDmk1oi/QmoN0UxQ6xasiiqZiVmQ7GA0ksQhH6CQktfAlbtOIuukVSlWyFp2f6LL8qGbbFFYwt5frtEDHnWuVlXtr4OZ7A6AAPgW30pq5Y+QkEq1HYxc8jz7KGa19o+fA4gABM/JewVSENaiTWq4GMYbsN+uw0fdf1mrU8zC8vdXrc2uF95YiNBP4LrhwD74/CLIhv2lWDprUnHVW8db5Vmq4y3Qlp9p15Dj+31xYqXr/vm7lFmoOjxN/duGTLuo/bCKZFEuIPuSAupYJxkMHkb+evBC8Nx3W6+mWydddo1SBcu4/1hdGoh0+ywpqQNv5PRwr9yEmn3MsNWxSvaEb9odUlV4+SKcbwYkfQSBG3ou2lnVG0ywwXn7q+omUDB550aru3SMHW2hIQtJK4FxCnCVxfPFmDVRXMxAEhXQS6GeMVEk9V14Ux047ozlp820xVtz88rqo3wWqMOXbvVH4biENehZDSMj4Ng8K2L7xVhxGIzpZCqBuNPcFLD9owftdPwWa5or29ZP3VKtHwjlKtAe7IaGvCz9t+bNPTKqtvxSCon6+RHPttFf5kPt4t1O7EDrXV3suqsrhKoRcWzmEasMxoNfOTlKp5L7X5ZHYvL32TIiqpFXYztAAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cluster-services-openshift.cloud.google.com
          resources:
          - telemetryconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - cluster-services-openshift.cloud.google.com
          resources:
          - telemetryconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - cluster-services-openshift.cloud.google.com
          resources:
          - telemetryconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: google-cloud-cluster-services-telemetry-agent-controller-manager
      - rules:
        - apiGroups:
          - admissionregistration.k8s.io
          - apiextensions.k8s.io
          - apiregistration.k8s.io
          - apiserver.openshift.io
          - apps.openshift.io
          - apps
          - authentication.k8s.io
          - authorization.k8s.io
          - authorization.openshift.io
          - autoscaling.openshift.io
          - autoscaling
          - batch
          - build.openshift.io
          - certificates.k8s.io
          - cloud.network.openshift.io
          - cloudcredential.openshift.io
          - config.openshift.io
          - console.openshift.io
          - controlplane.operator.openshift.io
          - coordination.k8s.io
          - discovery.k8s.io
          - events.k8s.io
          - external-secrets.io
          - flowcontrol.apiserver.k8s.io
          - helm.openshift.io
          - image.openshift.io
          - imageregistry.operator.openshift.io
          - infrastructure.cluster.x-k8s.io
          - ingress.operator.openshift.io
          - ipam.cluster.x-k8s.io
          - k8s.cni.cncf.io
          - k8s.ovn.org
          - machine.openshift.io
          - metal3.io
          - metrics.k8s.io
          - migration.k8s.io
          - monitoring.coreos.com
          - monitoring.googleapis.com
          - monitoring.openshift.io
          - network.operator.openshift.io
          - networking.k8s.io
          - node.k8s.io
          - olm.operatorframework.io
          - operator.openshift.io
          - operators.coreos.com
          - packages.operators.coreos.com
          - performance.openshift.io
          - policy.networking.k8s.io
          - policy
          - project.openshift.io
          - quota.openshift.io
          - rbac.authorization.k8s.io
          - route.openshift.io
          - samples.operator.openshift.io
          - scheduling.k8s.io
          - secrets-store.csi.x-k8s.io
          - security.internal.openshift.io
          - security.openshift.io
          - snapshot.storage.k8s.io
          - storage.k8s.io
          - template.openshift.io
          - tuned.openshift.io
          - user.openshift.io
          - whereabouts.cni.cncf.io
          resources:
          - apiservers
          - cloudcredentials
          - clusterpodmonitorings
          - clusterversions
          - csidrivers
          - customresourcedefinitions
          - daemonsets
          - deployments
          - externalsecrets
          - infrastructures
          - podmonitorings
          - routes
          - secretproviderclasses
          - secretstores
          - storageclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - bindings
          - componentstatuses
          - configmaps
          - endpoints
          - events
          - limitranges
          - namespaces
          - nodes
          - persistentvolumeclaims
          - persistentvolumes
          - pods
          - podtemplates
          - replicationcontrollers
          - resourcequotas
          - serviceaccounts
          - services
          verbs:
          - get
          - list
          - watch
        serviceAccountName: google-cloud-cluster-services-telemetry-agent-workloadagent-service-account
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: google-cloud-cluster-services-telemetry-agent
          control-plane: controller-manager
        name: google-cloud-cluster-services-telemetry-agent-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: us-docker.pkg.dev/workload-agent-products/cluster-services-for-openshift-telemetry/controller@sha256:05f5411d942e915c6dd05d629a9d068cc1fc90a8dce8bfe3d8f12e98bad22a28
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: google-cloud-cluster-services-telemetry-agent-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: google-cloud-cluster-services-telemetry-agent-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - google
  - cloud
  - workloadmanager
  - workload
  - manager
  links:
  - name: Cluster Services for OpenShift Telemetry
    url: https://docs.cloud.google.com/compute/docs/containers/openshift-overview
  maturity: stable
  provider:
    name: Google
    url: https://docs.cloud.google.com/
  version: 0.0.7
