---
merge: true
catalog_templates:
  - template_name: v4.14.yaml
    channels:
      - stable-3.x
    replaces: nutanixcsioperator.v3.7.1
  - template_name: v4.15.yaml
    channels:
      - stable-3.x
    replaces: nutanixcsioperator.v3.7.1
  - template_name: v4.16.yaml
    channels:
      - stable-3.x
    replaces: nutanixcsioperator.v3.7.1
  - template_name: v4.17.yaml
    channels:
      - stable-3.x
    replaces: nutanixcsioperator.v3.7.1
  - template_name: basic.yaml
    channels:
      - stable-3.x
    replaces: nutanixcsioperator.v3.7.1
