apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "mediation.turbonomic.ibm.com/v1alpha1",
          "kind": "OpenstackProbe",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "mediation-openstack-operator"
            },
            "name": "openstackprobe-sample"
          },
          "spec": {
            "image": {
              "imagePullPolicy": "Always",
              "registry": "icr.io/cpopen/turbonomic/mediation-openstack",
              "version": "8.19.2"
            },
            "numaConfig": "{\n  \"numa-topology\": {\n    \"hosts\": \n      [ \n        {\n          \"host-id\": \"computehci-0.turbo.lab.test\",\n          \"numas\": [\n            {\n              \"numa-id\": \"cell0\",\n              \"cpu\": {\n                \"used\": 4,\n                \"capacity\": 56,\n                \"vm-assigned\": [\n                  {\"vmId\": \"numa-test\", \"usage\": 4}\n                ]\n              },\n              \"pci\": [\n                {\n                  \"used\": 1,\n                  \"capacity\": 8,\n                  \"alias\": \"sriov_vf\",\n                  \"vendorId\": \"8086\",\n                  \"productId\": \"107d\",\n                  \"vm-assigned\": [\n                    {\"vmId\": \"numa-test\", \"usage\": 1}\n                  ]\n                }\n              ]\n            },\n            {\n              \"numa-id\": \"cell1\",\n                            \"cpu\": {\n                \"used\": 0,\n                \"capacity\": 56,\n                \"vm-assigned\": [\n                ]\n              },\n              \"pci\": [\n                {\n                  \"used\": 0,\n                  \"capacity\": 8,\n                  \"alias\": \"sriov_vf\",\n                  \"vendorId\": \"\",\n                  \"productId\": \"\",\n                  \"vm-assigned\": [\n                  ]\n                }\n              ]\n            }\n          ]\n        }\n      ]\n  }\n}\n",
            "turboProbeConfig": {
              "discoveryConfig": {
                "chunkSendDelayMillis": 0,
                "entityIdSuffix": "7ba7b140-6210-4b82-b672-f29a34081301",
                "numObjectsPerChunk": 5000,
                "requestPageSize": 100
              },
              "loggingLevel": 3,
              "restAPIConfig": {
                "turboServer": "",
                "turbonomicSecretCredentialsName": "turbonomic-credentials"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-03-24T11:01:20Z"
    operators.operatorframework.io/builder: operator-sdk-v1.41.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: mediation-openstack-operator.v8.19.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: TurbonomicClient is the Schema for the turbonomicclients API
        displayName: Turbonomic Openstack Probe
        kind: OpenstackProbe
        name: openstackprobes.mediation.turbonomic.ibm.com
        version: v1alpha1
  description: Turbonomic AI-powered Application Resource Management simultaneously optimizes performance, compliance, and cost in real time. Software manages the complete application stack, automatically. Applications are continually resourced to perform while satisfying business constraints.
  displayName: Turbonomic OpenStack Probe Operator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - charts.helm.k8s.io
              resources:
                - kubeturbos
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - mediation.turbonomic.ibm.com
              resources:
                - openstackprobes
                - versionmanagers
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - operators.coreos.com
              resources:
                - clusterserviceversions
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterrolebindings
                - clusterroles
              verbs:
                - create
                - delete
                - get
                - list
                - update
                - watch
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: openstack-probes-controller-manager
      deployments:
        - label:
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/name: mediation-openstack-operator
            control-plane: controller-manager
          name: openstack-probes-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                app.kubernetes.io/name: mediation-openstack-operator
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  app.kubernetes.io/name: mediation-openstack-operator
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --metrics-bind-address=:8443
                      - --leader-elect
                      - --health-probe-bind-address=:8081
                    command:
                      - /manager
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                    image: icr.io/cpopen/mediation-openstack-operator@sha256:9473580a03aa077f0b6067e8eeede2d11746436216a52a373bcb35fef0e1e4c7
                    imagePullPolicy: Always
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 10m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                securityContext:
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
                serviceAccountName: openstack-probes-controller-manager
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
            - apiGroups:
                - ""
              resources:
                - configmaps
                - endpoints
                - pods
                - pods/exec
                - secrets
                - serviceaccounts
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - apps
              resources:
                - daemonsets
                - deployments
                - replicasets
                - statefulsets
              verbs:
                - create
                - delete
                - get
                - list
                - update
                - watch
            - apiGroups:
                - apps.openshift.io
              resources:
                - deploymentconfigs
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - mediation.turbonomic.ibm.com
              resources:
                - openstackprobes
                - versionmanagers
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - mediation.turbonomic.ibm.com
              resources:
                - openstackprobes/finalizers
                - versionmanagers/finalizers
              verbs:
                - update
            - apiGroups:
                - mediation.turbonomic.ibm.com
              resources:
                - openstackprobes/status
                - versionmanagers/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
                - roles
              verbs:
                - create
                - delete
                - get
                - list
                - update
                - watch
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
              verbs:
                - create
                - delete
                - get
                - list
                - watch
            - apiGroups:
                - security.openshift.io
              resourceNames:
                - nonroot
                - privileged
              resources:
                - securitycontextconstraints
              verbs:
                - use
          serviceAccountName: openstack-probes-controller-manager
    strategy: deployment
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - monitoring
  links:
    - name: Mediation Openstack Operator
      url: https://mediation-openstack-operator.domain
  maintainers:
    - email: turbodeploy@turbonomic.com
      name: turbodeploy
  maturity: alpha
  provider:
    name: openstack-probe-operator
  relatedImages:
    - image: icr.io/cpopen/mediation-openstack-operator@sha256:9473580a03aa077f0b6067e8eeede2d11746436216a52a373bcb35fef0e1e4c7
      name: manager
  version: 8.19.2
