{
 "title": "Airlock Microgateway System - Metrics",
 "description": "Metrics on system resources of the Airlock Microgateway Engine and network I/O on pod level.",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "gateway_kind",
    "label": "Gateway Kind",
    "query": {
     "query": "label_values(microgateway_build_info,gateway_kind)"
    }
   },
   {
    "name": "namespace",
    "label": "Gateway Namespace",
    "query": {
     "query": "label_values(microgateway_build_info{gateway_kind=\"$gateway_kind\"},namespace)"
    }
   },
   {
    "name": "gateway_name",
    "label": "Gateway Name",
    "query": {
     "query": "label_values(microgateway_build_info{namespace=~\"$namespace\", gateway_kind=~\"$gateway_kind\"},gateway)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(microgateway_build_info{gateway_kind=\"$gateway_kind\", namespace=\"$namespace\", gateway=\"$gateway_name\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Airlock Microgateway Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container Readiness",
   "type": "stat",
   "description": "Readiness status of the Airlock Microgateway Engine container.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{container=\"airlock-microgateway-engine\",pod=\"${pod}\"}",
     "legendFormat": "Health"
    }
   ]
  },
  { "title": "Container Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage (cores)",
   "type": "timeseries",
   "description": "CPU usage over time of the Airlock Microgateway Engine container.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": " sum(kube_pod_container_resource_limits{pod=\"${pod}\",container=\"airlock-microgateway-engine\",resource=\"cpu\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": " sum(kube_pod_container_resource_requests{pod=\"${pod}\",container=\"airlock-microgateway-engine\",resource=\"cpu\"})",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=\"${pod}\",container=\"airlock-microgateway-engine\"}[$__rate_interval])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage over time of the Airlock Microgateway Engine container.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{pod=\"${pod}\",container=\"airlock-microgateway-engine\",resource=\"memory\"}",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=\"${pod}\", container=\"airlock-microgateway-engine\", resource=\"memory\"}",
     "legendFormat": "Memory Request"
    },
    {
     "expr": "container_memory_usage_bytes{pod=\"${pod}\",container=\"airlock-microgateway-engine\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  { "title": "Pod Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Network I/O of the selected pod over time.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{pod=\"${pod}\"}[$__rate_interval])",
     "legendFormat": "Received"
    }
   ]
  }
 ]
}