apiVersion: v1
kind: Service
metadata:
  annotations:
    containerImage: harness/gitops-agent-controller@sha256:17cedf72c8febd48a6d03a926d6737fa2e31cc2ae0f7e8cab3f849d602b10d15
    createdAt: "2026-06-25T14:09:17Z"
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitops-operator
    control-plane: harness-gitops-operator
  name: harness-gitops-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: harness-gitops-operator
status:
  loadBalancer: {}
