apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    containerImage: harness/gitops-agent-controller@sha256:17cedf72c8febd48a6d03a926d6737fa2e31cc2ae0f7e8cab3f849d602b10d15
    createdAt: "2026-06-25T14:09:17Z"
  creationTimestamp: null
  name: harness-gitops-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
