apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jamaibase-operator
  name: jamaibase-operator-jamaibase-viewer-role
rules:
- apiGroups:
  - apps.jamaibase.com
  resources:
  - jamaibases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.jamaibase.com
  resources:
  - jamaibases/status
  verbs:
  - get
