apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: edb-hcp-operator
    control-plane: edb-hcp-operator
  name: edb-hcp-operator-hmfederationtoken-admin-role
rules:
- apiGroups:
  - edbpgai.edb.com
  resources:
  - hmfederationtokens
  verbs:
  - '*'
- apiGroups:
  - edbpgai.edb.com
  resources:
  - hmfederationtokens/status
  verbs:
  - get
