apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: tawon
  name: tawon-operator-eob-eob-operator
rules:
- apiGroups:
  - tawon.mantisnet.com
  resources:
  - directives
  - streams
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - tawon.mantisnet.com
  resources:
  - streamstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
