apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: airlock-microgateway
    app.kubernetes.io/name: microgateway-operator
    app.kubernetes.io/part-of: microgateway
    app.kubernetes.io/version: 5.0.6
  name: airlock-microgateway
spec:
  endpoints:
  - path: /metrics
    port: metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: airlock-microgateway
      app.kubernetes.io/name: microgateway-operator
