apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: google-cloud-cluster-services-telemetry-agent-workloadagent-service-account-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: google-cloud-cluster-services-telemetry-agent-workloadagent-service-account-role
subjects:
- kind: ServiceAccount
  name: google-cloud-cluster-services-telemetry-agent-workloadagent-service-account
  namespace: google-cloud-cluster-services-telemetry-agent-system
