---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: google-cloud-cluster-services-telemetry-agent-workloadagent-service-account-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  - apiextensions.k8s.io
  - apiregistration.k8s.io
  - apiserver.openshift.io
  - apps.openshift.io
  - apps
  - authentication.k8s.io
  - authorization.k8s.io
  - authorization.openshift.io
  - autoscaling.openshift.io
  - autoscaling
  - batch
  - build.openshift.io
  - certificates.k8s.io
  - cloud.network.openshift.io
  - cloudcredential.openshift.io
  - config.openshift.io
  - console.openshift.io
  - controlplane.operator.openshift.io
  - coordination.k8s.io
  - discovery.k8s.io
  - events.k8s.io
  - external-secrets.io
  - flowcontrol.apiserver.k8s.io
  - helm.openshift.io
  - image.openshift.io
  - imageregistry.operator.openshift.io
  - infrastructure.cluster.x-k8s.io
  - ingress.operator.openshift.io
  - ipam.cluster.x-k8s.io
  - k8s.cni.cncf.io
  - k8s.ovn.org
  - machine.openshift.io
  - metal3.io
  - metrics.k8s.io
  - migration.k8s.io
  - monitoring.coreos.com
  - monitoring.googleapis.com
  - monitoring.openshift.io
  - network.operator.openshift.io
  - networking.k8s.io
  - node.k8s.io
  - olm.operatorframework.io
  - operator.openshift.io
  - operators.coreos.com
  - packages.operators.coreos.com
  - performance.openshift.io
  - policy.networking.k8s.io
  - policy
  - project.openshift.io
  - quota.openshift.io
  - rbac.authorization.k8s.io
  - samples.operator.openshift.io
  - scheduling.k8s.io
  - secrets-store.csi.x-k8s.io
  - security.internal.openshift.io
  - security.openshift.io
  - snapshot.storage.k8s.io
  - storage.k8s.io
  - template.openshift.io
  - tuned.openshift.io
  - user.openshift.io
  - whereabouts.cni.cncf.io
  resources:
  - apiservers
  - cloudcredentials
  - clusterpodmonitorings
  - clusterversions
  - csidrivers
  - customresourcedefinitions
  - daemonsets
  - deployments
  - externalsecrets
  - infrastructures
  - podmonitorings
  - secretproviderclasses
  - secretstores
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - componentstatuses
  - configmaps
  - endpoints
  - events
  - limitranges
  - namespaces
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - podtemplates
  - replicationcontrollers
  - resourcequotas
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
