apiVersion: v1
kind: Service
metadata:
  annotations:
    containerImage: harness/gitops-agent-controller@sha256:caf81f8aef723488fc09651494cd40c30a7d232a3580aca7aec0adc78c553176
    createdAt: "2026-09-30T22:05:51Z"
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitops-operator
    control-plane: harness-gitops-operator
  name: harness-gitops-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: harness-gitops-operator
status:
  loadBalancer: {}
