apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: google-cloud-workload-agent-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
