---
catalog_templates:
  - template_name: v4.18.yaml
    channels: stable
    replaces: xspc-operator.v1.16.1
    skips:
      - xspc-operator.v1.15.0
  - template_name: v4.19.yaml
    channels: stable
    replaces: xspc-operator.v1.16.1
    skips:
      - xspc-operator.v1.15.0
  - template_name: v4.20.yaml
    channels: stable
    replaces: xspc-operator.v1.16.1
    skips:
      - xspc-operator.v1.15.0
  - template_name: v4.21.yaml
    channels: stable
    replaces: xspc-operator.v1.16.1
    skips:
      - xspc-operator.v1.15.0

