---
catalog_templates:
  - template_name: v4.18.yaml
    channels: [stable, v26.7]
    replaces: gpu-operator-certified.v26.3.3
    skipRange: '>=1.9.0 <26.7.0'
  - template_name: v4.19.yaml
    channels: [stable, v26.7]
    replaces: gpu-operator-certified.v26.3.3
    skipRange: '>=1.9.0 <26.7.0'
  - template_name: v4.20.yaml
    channels: [stable, v26.7]
    replaces: gpu-operator-certified.v26.3.3
    skipRange: '>=1.9.0 <26.7.0'
  - template_name: v4.21.yaml
    channels: [stable, v26.7]
    replaces: gpu-operator-certified.v26.3.3
    skipRange: '>=1.9.0 <26.7.0'
  - template_name: v4.22.yaml
    channels: [stable, v26.7]
    replaces: gpu-operator-certified.v26.3.3
    skipRange: '>=1.9.0 <26.7.0'
