apiVersion: v1
data:
  properties.yaml: "---\n# Not used at runtime. Kept as a compatibility stub for external\
    \ references.\nversion: 0.1.0\nspec:\n  units: []\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: spark-k8s-operator
    app.kubernetes.io/name: spark-k8s-operator
    app.kubernetes.io/version: 26.7.0
    stackable.tech/vendor: Stackable
  name: spark-k8s-operator-configmap
