apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2026-03-23T14:53:14Z"
    operators.operatorframework.io/builder: operator-sdk-v1.41.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: openstack-probes-deploy.v8.19.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Turbonomic AI-powered Application Resource Management simultaneously
    optimizes performance, compliance, and cost in real time. Software manages the
    complete application stack, automatically. Applications are continually resourced
    to perform while satisfying business constraints.
  displayName: Turbonomic OpenStack Probe Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - monitoring
  links:
  - name: Openstack Probes Deploy
    url: https://openstack-probes-deploy.domain
  maintainers:
  - email: turbodeploy@turbonomic.com
    name: turbodeploy
  maturity: alpha
  provider:
    name: openstack-probe-operator
  version: 8.19.3
