apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: app-insights-operator
  name: app-insights-operator-scc-privileged-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: randoli-obs-prometheus-node-exporter
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-obs-kube-state-metrics
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-otel-collector
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-obs-vector
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-obs-vector-agent
  namespace: randoli-agents
- kind: ServiceAccount
  name: vector-configcheck
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-sec-kubescape
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-sec-kubescape-operator
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-sec-kubescape-storage
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-sec-kubevuln
  namespace: randoli-agents
- kind: ServiceAccount
  name: randoli-sec-kubescape-node-agent
  namespace: randoli-agents
