apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: mcpconfigurations.mcp.ai.randoli.io
spec:
  group: mcp.ai.randoli.io
  names:
    kind: MCPConfiguration
    plural: mcpconfigurations
    shortNames:
    - mcpconf
    singular: mcpconfiguration
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.type
      name: Type
      type: string
    - jsonPath: .spec.category
      name: Category
      type: string
    - jsonPath: .spec.transport
      name: Transport
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              allowedTools:
                items:
                  type: string
                type: array
              category:
                type: string
              headers:
                additionalProperties:
                  type: string
                type: object
              prompt:
                type: string
              transport:
                enum:
                - streamable_http
                - sse
                - stdio
                type: string
              type:
                type: string
              url:
                format: uri
                type: string
            required:
            - type
            - transport
            - url
            - prompt
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
