apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "workloadagent.cloud.google.com/v1alpha1",
          "kind": "WorkloadAgentConfig",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "google-cloud-workload-agent"
            },
            "name": "workloadagent"
          },
          "spec": {
            "enabled": true,
            "imageVersion": "v0.0.1",
            "serviceAccountCredentialsPath": "\u003c/var/run/secrets/cloud.google.com/serviceaccount/file-name\u003e",
            "serviceAccountCredentialsSecretName": "\u003csecret-name\u003e"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-05-03T07:43:33Z"
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "true"
    operators.operatorframework.io/builder: operator-sdk-v1.39.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: google-cloud-workload-agent.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: WorkloadAgentConfig is the Schema for the workloadagentconfigs
        API
      displayName: Workload Agent Config
      kind: WorkloadAgentConfig
      name: workloadagentconfigs.workloadagent.cloud.google.com
      specDescriptors:
      - description: Enabled defines if the workloadagent should be enabled
        displayName: Enabled
        path: enabled
      - description: The repository of the workload agent image to use.
        displayName: Image Repository
        path: imageRepository
      - description: The version of the workload agent image to use.
        displayName: Image Version
        path: imageVersion
      - description: |-
          The name of the Kubernetes configmap containing the service account's credential configuration
          JSON file.
        displayName: Service Account Credential Config Config Map Name
        path: serviceAccountCredentialConfigConfigMapName
      - description: |-
          The path of the service account's credentials stored as a secret. This is the credential that
          will be used to authenticate with the Google Cloud Workload Manager.
          For example: "/var/run/secrets/cloud.google.com/serviceaccount/file-name"
        displayName: Service Account Credentials Path
        path: serviceAccountCredentialsPath
      - description: |-
          The name of the Kubernetes secret containing the service account's credentials. This is the
          credential that will be used to authenticate with the Google Cloud Workload Manager.
        displayName: Service Account Credentials Secret Name
        path: serviceAccountCredentialsSecretName
      - description: The audience of the service account's token used for workload
          identity authentication requests.
        displayName: Service Account Token Audience
        path: serviceAccountTokenAudience
      statusDescriptors:
      - description: |-
          For further information see: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
          Conditions store the status conditions of the Openshift instances
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: Operator for Google Cloud Compute Workloads agent
  displayName: Google Cloud Compute Workloads agent
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAADY0lEQVR4AcXVA5QkVxSA4f++6q7GoHdPsmPEtm3btm3btpOD2LZtc22MPdPuqneDORn02l8Zz2JhE2ZBt9suRjB3AB47YWQNVCpRySJOCzi/gfMu0eAr8tprnXOVgJ6wbpAeczGJ4Ln4pgg/ACq9BwIS6Dus43aicptJNN8in33mkceQR09ZrZqc9x2iVwFFIMzGEDVynV9c8anuvP8w8gQYQO+uqKE58Tlht5akBV8gq71HzgEMICD/F8jQSwDpopCumZZAX8ClrOcVylK1BBSWTENxFhyFiN9KUJ/BcCHImRZ9EKgTFBDAvuOEsvvIiy9mZ14CN3oeGdYBYGgaEiEAn0juBtJFt8rbn8UZQNdd9yyGVV+I0fVNmP37Is8jAPopYZxIAzmJ0RmEpAMpxzKt4Fi5ZtLjzAcDQCyyFyIxokCRB7EsOP79fZHPdwJG9iNKr4hCgU0SydwA8y8AoLAcBiQsYEFd+chsG29iBta6QS0zo0o/Oem3S+WRAABKDQiIQY2ioiOZFyIDb0v7SpDPBlDmk1oi/QmoN0UxQ6xasiiqZiVmQ7GA0ksQhH6CQktfAlbtOIuukVSlWyFp2f6LL8qGbbFFYwt5frtEDHnWuVlXtr4OZ7A6AAPgW30pq5Y+QkEq1HYxc8jz7KGa19o+fA4gABM/JewVSENaiTWq4GMYbsN+uw0fdf1mrU8zC8vdXrc2uF95YiNBP4LrhwD74/CLIhv2lWDprUnHVW8db5Vmq4y3Qlp9p15Dj+31xYqXr/vm7lFmoOjxN/duGTLuo/bCKZFEuIPuSAupYJxkMHkb+evBC8Nx3W6+mWydddo1SBcu4/1hdGoh0+ywpqQNv5PRwr9yEmn3MsNWxSvaEb9odUlV4+SKcbwYkfQSBG3ou2lnVG0ywwXn7q+omUDB550aru3SMHW2hIQtJK4FxCnCVxfPFmDVRXMxAEhXQS6GeMVEk9V14Ux047ozlp820xVtz88rqo3wWqMOXbvVH4biENehZDSMj4Ng8K2L7xVhxGIzpZCqBuNPcFLD9owftdPwWa5or29ZP3VKtHwjlKtAe7IaGvCz9t+bNPTKqtvxSCon6+RHPttFf5kPt4t1O7EDrXV3suqsrhKoRcWzmEasMxoNfOTlKp5L7X5ZHYvL32TIiqpFXYztAAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - workloadagent.cloud.google.com
          resources:
          - workloadagentconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - workloadagent.cloud.google.com
          resources:
          - workloadagentconfigs/finalizers
          verbs:
          - update
        - apiGroups:
          - workloadagent.cloud.google.com
          resources:
          - workloadagentconfigs/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: google-cloud-workload-agent-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: google-cloud-workload-agent
          control-plane: controller-manager
        name: google-cloud-workload-agent-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: us-docker.pkg.dev/workload-agent-products/google-cloud-workload-agent-operator/google-cloud-workload-agent-controller:v0.0.1
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: google-cloud-workload-agent-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: google-cloud-workload-agent-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - google
  - cloud
  - workloadmanager
  - workload
  - manager
  links:
  - name: Google Cloud Compute Workloads agent
    url: https://github.com/GoogleCloudPlatform/workloadagent
  maturity: alpha
  provider:
    name: Google LLC
    url: https://github.com/GoogleCloudPlatform/workloadagent
  version: 0.0.1
