apiVersion: v1
data:
  0_linbit_sds_images.yaml: |
    base: drbd.io
    components:
      drbd-module-loader:
        digest: sha256:6542da92163845b3d591368f349c8a708b5ca23c7afb88ca0194694e4b6dab07
        image: drbd9-rhel9
        match:
        - digest: sha256:003ee3ea13ae0aeb6fb55c9a6c16dd3cff0d60c98322501a9b4d2dd02e613256
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux 8\.
          precompiled: true
        - digest: sha256:6542da92163845b3d591368f349c8a708b5ca23c7afb88ca0194694e4b6dab07
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux 9\.
          precompiled: true
        - digest: sha256:b34121bdf2c2d744ce57f8fbc0d647250e7ec1e1d0f9aa034a0fe4db14697d6b
          image: drbd9-rhel10
          osImage: Red Hat Enterprise Linux 10\.
          precompiled: true
        - digest: sha256:b34121bdf2c2d744ce57f8fbc0d647250e7ec1e1d0f9aa034a0fe4db14697d6b
          image: drbd9-rhel10
          osImage: Red Hat Enterprise Linux CoreOS 10\.
          precompiled: true
        - digest: sha256:6542da92163845b3d591368f349c8a708b5ca23c7afb88ca0194694e4b6dab07
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux CoreOS 9|(41[3-9])
          precompiled: true
        - digest: sha256:003ee3ea13ae0aeb6fb55c9a6c16dd3cff0d60c98322501a9b4d2dd02e613256
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux CoreOS
          precompiled: true
        - digest: sha256:003ee3ea13ae0aeb6fb55c9a6c16dd3cff0d60c98322501a9b4d2dd02e613256
          image: drbd9-rhel8
          osImage: CentOS Linux 8
          precompiled: true
        - digest: sha256:003ee3ea13ae0aeb6fb55c9a6c16dd3cff0d60c98322501a9b4d2dd02e613256
          image: drbd9-rhel8
          osImage: AlmaLinux 8
          precompiled: true
        - digest: sha256:6542da92163845b3d591368f349c8a708b5ca23c7afb88ca0194694e4b6dab07
          image: drbd9-rhel9
          osImage: AlmaLinux 9
          precompiled: true
        - digest: sha256:b34121bdf2c2d744ce57f8fbc0d647250e7ec1e1d0f9aa034a0fe4db14697d6b
          image: drbd9-rhel10
          osImage: AlmaLinux 10
          precompiled: true
        - digest: sha256:003ee3ea13ae0aeb6fb55c9a6c16dd3cff0d60c98322501a9b4d2dd02e613256
          image: drbd9-rhel8
          osImage: Oracle Linux Server 8\.
          precompiled: true
        - digest: sha256:6542da92163845b3d591368f349c8a708b5ca23c7afb88ca0194694e4b6dab07
          image: drbd9-rhel9
          osImage: Oracle Linux Server 9\.
          precompiled: true
        - digest: sha256:b34121bdf2c2d744ce57f8fbc0d647250e7ec1e1d0f9aa034a0fe4db14697d6b
          image: drbd9-rhel10
          osImage: Oracle Linux Server 10\.
          precompiled: true
        - digest: sha256:003ee3ea13ae0aeb6fb55c9a6c16dd3cff0d60c98322501a9b4d2dd02e613256
          image: drbd9-rhel8
          osImage: Rocky Linux 8
          precompiled: true
        - digest: sha256:6542da92163845b3d591368f349c8a708b5ca23c7afb88ca0194694e4b6dab07
          image: drbd9-rhel9
          osImage: Rocky Linux 9
          precompiled: true
        - digest: sha256:b34121bdf2c2d744ce57f8fbc0d647250e7ec1e1d0f9aa034a0fe4db14697d6b
          image: drbd9-rhel10
          osImage: Rocky Linux 10
          precompiled: true
        tag: v9.3.4
      drbd-reactor:
        digest: sha256:e7bcf410acdd31f98d2c88e425042f2ef7750d52142d2bdc2f07b9b57ee836ed
        image: drbd-reactor
        tag: v1.12.0
      drbd-shutdown-guard:
        digest: sha256:16793f5aa10b46b198806c9198216fbd1aaec31269c28adea7e526dd17ff6f57
        image: drbd-shutdown-guard
        tag: v1.1.2
      ha-controller:
        digest: sha256:850fbc36955f1f6fc59a6d83028f726b1c5cd21cb912d59a065239df7ac2d810
        image: linstor-k8s-ha-controller
        tag: v1.3.4
      ktls-utils:
        digest: sha256:3351a6e0fc048fe1544499095cdb8fdd221e832cecfa8a9a01f046c271991138
        image: ktls-utils
        tag: v1.2.1
      linstor-affinity-controller:
        digest: sha256:76f25c6a6cfdb430a1f7459ab91a7af5ca8130b95cfd9a413e5e16966ee06bca
        image: linstor-affinity-controller
        tag: v1.5.0
      linstor-controller:
        digest: sha256:dca6c9ec4cd0d01b95ccfe7d6f737ab11f11a3cdc315401ed80501f3d7241922
        image: linstor-controller
        tag: v1.35.2
      linstor-csi:
        digest: sha256:52588fb31d69ab910fa52e54cccbe4707d61b37516981455255af8ccef4800d4
        image: linstor-csi
        tag: v1.13.1
      linstor-satellite:
        digest: sha256:698e91fb5c24dc0cb2695c97ededa87097a4ad0248eacd4bb2e3d18b1a6489fe
        image: linstor-satellite
        tag: v1.35.2
      nfs-server:
        digest: sha256:2a5e4b140bcbfa09468126d7e4d0fcff1d49a14952c19c40b6bc62929839ad2d
        image: nfs-server
        tag: v1.13.1
  0_redhat_ose_images.yaml: |
    base: registry.redhat.io/openshift4
    components:
      csi-attacher:
        digest: sha256:403c294ff98d97ab70c27cdd7b98d60c649225885289ff62e5544b47c578afc2
        image: ose-csi-external-attacher-rhel9
        tag: latest
      csi-livenessprobe:
        digest: sha256:420901dbf153d586fec7cd32fe0f8f0bf1b12565d324a7ba8886671bc88de9c0
        image: ose-csi-livenessprobe-rhel9
        tag: latest
      csi-node-driver-registrar:
        digest: sha256:8065c72345946e0b5845640b3f33332f7a3d1891ec603b5591b70ddab245f15d
        image: ose-csi-node-driver-registrar-rhel9
        tag: latest
      csi-provisioner:
        digest: sha256:6d93ffaa751329c6dc83fe34913e4b0f668d0060497f017be68760157c9d77fe
        image: ose-csi-external-provisioner-rhel9
        tag: latest
      csi-resizer:
        digest: sha256:1bc398302896e0c69fc1713d27317dc1bfc519ff2ae304d08393e1fbf9e78196
        image: ose-csi-external-resizer-rhel9
        tag: latest
      csi-snapshotter:
        digest: sha256:6faa44e13191e8687cb1c82735510dc9dd0ce18d95fbd2d7a8f0f2e3b7c80973
        image: ose-csi-external-snapshotter-rhel9
        tag: latest
  0_sig_storage_images.yaml: |
    base: registry.k8s.io/sig-storage
    components:
      csi-external-health-monitor-controller:
        digest: sha256:430c1f2267152ce6e4547ebbad225a2b399d03e5894f2f39ba233a38e4750a47
        image: csi-external-health-monitor-controller
        tag: v0.18.0
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: linbit-sds
  name: linstor-operator-image-config
