---
catalog_templates:
  - template_name: v4.18.yaml
    channels: [stable]
    replaces: minio-object-store-operator.v2026.7.9050221
  - template_name: v4.19.yaml
    channels: [stable]
    replaces: minio-object-store-operator.v2026.7.9050221
  - template_name: v4.20.yaml
    channels: [stable]
    replaces: minio-object-store-operator.v2026.7.9050221
  - template_name: v4.21.yaml
    channels: [stable]
    replaces: minio-object-store-operator.v2026.7.9050221
  - template_name: v4.22.yaml
    channels: [stable]
    replaces: minio-object-store-operator.v2026.7.9050221
