apiVersion: v1
data:
  minkms: |
    image: "quay.io/minio/aistor/minkms:RELEASE.2026-09-16T11-16-36Z"
  minkms-sidecar: |
    image: "quay.io/minio/aistor/minkms-sidecar:RELEASE.2026-09-18T18-00-03Z"
kind: ConfigMap
metadata:
  name: minkms-operator-default
