catalog_templates:
  - template_name: v4.16.yaml
    channels: ["5.0"]
    replaces: airlock-microgateway.v5.0.7
    skipRange: '>=5.0.0 <5.0.8'
  - template_name: v4.17.yaml
    channels: ["5.0"]
    replaces: airlock-microgateway.v5.0.7
    skipRange: '>=5.0.0 <5.0.8'
  - template_name: v4.18.yaml
    channels: ["5.0"]
    replaces: airlock-microgateway.v5.0.7
    skipRange: '>=5.0.0 <5.0.8'
  - template_name: v4.19.yaml
    channels: ["5.0"]
    replaces: airlock-microgateway.v5.0.7
    skipRange: '>=5.0.0 <5.0.8'
  - template_name: v4.20.yaml
    channels: ["5.0"]
    replaces: airlock-microgateway.v5.0.7
    skipRange: '>=5.0.0 <5.0.8'
  - template_name: v4.21.yaml
    channels: ["5.0"]
    replaces: airlock-microgateway.v5.0.7
    skipRange: '>=5.0.0 <5.0.8'
  - template_name: v4.22.yaml
    channels: ["5.0"]
    replaces: airlock-microgateway.v5.0.7
    skipRange: '>=5.0.0 <5.0.8'
