apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    containerImage: harness/gitops-agent-controller@sha256:788e59da96860122775b86df355f8c4ef6398f04877b3264f68b3b281e3597ba
    createdAt: "2026-08-13T12:28:55Z"
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitops-operator
  name: harness-gitops-operator-gitopsagent-editor-role
rules:
- apiGroups:
  - gitops.harness.io
  resources:
  - gitopsagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.harness.io
  resources:
  - gitopsagents/status
  verbs:
  - get
