---
# Source: release-config/templates/release-config.yaml
catalog_templates:
  - template_name: v4.20.yaml
    channels: [stable]
    replaces: dell-csm-operator-certified.v1.12.2
  - template_name: v4.21.yaml
    channels: [stable]
    replaces: dell-csm-operator-certified.v1.12.2
  - template_name: v4.22.yaml
    channels: [stable]
    replaces: dell-csm-operator-certified.v1.12.2
