catalog_templates:
  - template_name: v4.16.yaml
    channels: ["4.8"]
    replaces: airlock-microgateway.v4.8.11
    skipRange: '>=4.8.0 <4.8.12'
  - template_name: v4.17.yaml
    channels: ["4.8"]
    replaces: airlock-microgateway.v4.8.11
    skipRange: '>=4.8.0 <4.8.12'
  - template_name: v4.18.yaml
    channels: ["4.8"]
    replaces: airlock-microgateway.v4.8.11
    skipRange: '>=4.8.0 <4.8.12'
  - template_name: v4.19.yaml
    channels: ["4.8"]
    replaces: airlock-microgateway.v4.8.11
    skipRange: '>=4.8.0 <4.8.12'
  - template_name: v4.20.yaml
    channels: ["4.8"]
    replaces: airlock-microgateway.v4.8.11
    skipRange: '>=4.8.0 <4.8.12'
  - template_name: v4.21.yaml
    channels: ["4.8"]
    replaces: airlock-microgateway.v4.8.11
    skipRange: '>=4.8.0 <4.8.12'
  - template_name: v4.22.yaml
    channels: ["4.8"]
    replaces: airlock-microgateway.v4.8.11
    skipRange: '>=4.8.0 <4.8.12'
