apiVersion: v1
data:
  0_linbit_sds_images.yaml: |
    base: drbd.io
    components:
      drbd-module-loader:
        digest: sha256:a6d524d62c73b13037c766afe13522de52dbf6c8f99f80181fa1bf1656bb9fc1
        image: drbd9-rhel9
        match:
        - digest: sha256:2c7020f72ded67703eeac6bf44f2621d5d1b76677499765b233df3793acbd3a3
          image: drbd9-rhel7
          osImage: Red Hat Enterprise Linux Server 7\.
          precompiled: true
        - digest: sha256:0ec36fc29f0f37593f2cd3ff103574d3e2befcd760f72f8e0017a874a8097fb5
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux 8\.
          precompiled: true
        - digest: sha256:a6d524d62c73b13037c766afe13522de52dbf6c8f99f80181fa1bf1656bb9fc1
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux 9\.
          precompiled: true
        - digest: sha256:4c84c7f8ad9f99b72e5529826e3737dbc6a00f155475ac5f2bbd24c3f5b52325
          image: drbd9-rhel10
          osImage: Red Hat Enterprise Linux 10\.
          precompiled: true
        - digest: sha256:a6d524d62c73b13037c766afe13522de52dbf6c8f99f80181fa1bf1656bb9fc1
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux CoreOS 9|(41[3-9])
          precompiled: true
        - digest: sha256:0ec36fc29f0f37593f2cd3ff103574d3e2befcd760f72f8e0017a874a8097fb5
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux CoreOS
          precompiled: true
        - digest: sha256:2c7020f72ded67703eeac6bf44f2621d5d1b76677499765b233df3793acbd3a3
          image: drbd9-rhel7
          osImage: CentOS Linux 7
          precompiled: true
        - digest: sha256:0ec36fc29f0f37593f2cd3ff103574d3e2befcd760f72f8e0017a874a8097fb5
          image: drbd9-rhel8
          osImage: CentOS Linux 8
          precompiled: true
        - digest: sha256:0ec36fc29f0f37593f2cd3ff103574d3e2befcd760f72f8e0017a874a8097fb5
          image: drbd9-rhel8
          osImage: AlmaLinux 8
          precompiled: true
        - digest: sha256:a6d524d62c73b13037c766afe13522de52dbf6c8f99f80181fa1bf1656bb9fc1
          image: drbd9-rhel9
          osImage: AlmaLinux 9
          precompiled: true
        - digest: sha256:4c84c7f8ad9f99b72e5529826e3737dbc6a00f155475ac5f2bbd24c3f5b52325
          image: drbd9-rhel10
          osImage: AlmaLinux 10
          precompiled: true
        - digest: sha256:0ec36fc29f0f37593f2cd3ff103574d3e2befcd760f72f8e0017a874a8097fb5
          image: drbd9-rhel8
          osImage: Oracle Linux Server 8\.
          precompiled: true
        - digest: sha256:a6d524d62c73b13037c766afe13522de52dbf6c8f99f80181fa1bf1656bb9fc1
          image: drbd9-rhel9
          osImage: Oracle Linux Server 9\.
          precompiled: true
        - digest: sha256:4c84c7f8ad9f99b72e5529826e3737dbc6a00f155475ac5f2bbd24c3f5b52325
          image: drbd9-rhel10
          osImage: Oracle Linux Server 10\.
          precompiled: true
        - digest: sha256:0ec36fc29f0f37593f2cd3ff103574d3e2befcd760f72f8e0017a874a8097fb5
          image: drbd9-rhel8
          osImage: Rocky Linux 8
          precompiled: true
        - digest: sha256:a6d524d62c73b13037c766afe13522de52dbf6c8f99f80181fa1bf1656bb9fc1
          image: drbd9-rhel9
          osImage: Rocky Linux 9
          precompiled: true
        - digest: sha256:4c84c7f8ad9f99b72e5529826e3737dbc6a00f155475ac5f2bbd24c3f5b52325
          image: drbd9-rhel10
          osImage: Rocky Linux 10
          precompiled: true
        tag: v9.2.18
      drbd-reactor:
        digest: sha256:f9459826dd517744f2177f7d85e3325ce97a5806e9ac3e48916ec759ee4056b6
        image: drbd-reactor
        tag: v1.11.0
      drbd-shutdown-guard:
        digest: sha256:16793f5aa10b46b198806c9198216fbd1aaec31269c28adea7e526dd17ff6f57
        image: drbd-shutdown-guard
        tag: v1.1.2
      ha-controller:
        digest: sha256:13bc9273fe4b752aaa9a0aa0add2c4261589f80fae2d367ab36728b8abc93d0e
        image: linstor-k8s-ha-controller
        tag: v1.3.2
      ktls-utils:
        digest: sha256:3351a6e0fc048fe1544499095cdb8fdd221e832cecfa8a9a01f046c271991138
        image: ktls-utils
        tag: v1.2.1
      linstor-affinity-controller:
        digest: sha256:1988a74dbf44ff12e3204b8d679a1396d08e8a13bb84e970cf984fc0e56e401e
        image: linstor-affinity-controller
        tag: v1.4.0
      linstor-controller:
        digest: sha256:ed8bdafc7616de76f730d83624aa11cec399d723874d20f8f3cff91ffa9478a5
        image: linstor-controller
        tag: v1.33.2
      linstor-csi:
        digest: sha256:654017bf15259254f747cc182dbcebf39a151d0ebc9b6f0e97fec1cfa9f6d45c
        image: linstor-csi
        tag: v1.11.0
      linstor-satellite:
        digest: sha256:ecc25731fe79a88565a753ba7d0e156ca17c2c0662a67a3fe1a400f2cc6d6379
        image: linstor-satellite
        tag: v1.33.2
      nfs-server:
        digest: sha256:02032a18b2df4002bbc6fa925e9e61750cc4478c28630322f20e991d643020d4
        image: nfs-server
        tag: v1.11.0
  0_redhat_ose_images.yaml: |
    base: registry.redhat.io/openshift4
    components:
      csi-attacher:
        digest: sha256:09ee4b866404f3c3e55fa921fcad923ca6d481f52386cb1ef4b0b4065a98eb3a
        image: ose-csi-external-attacher-rhel9
        tag: latest
      csi-livenessprobe:
        digest: sha256:eeb42862b9f6f5fecc350992d65d3e3f1d3ef6a69e372f14f3ddb84f203fccd1
        image: ose-csi-livenessprobe-rhel9
        tag: latest
      csi-node-driver-registrar:
        digest: sha256:b733294b20191202f1b075e4023c66dd03b1b6e03002f87e480ed12d542e2aee
        image: ose-csi-node-driver-registrar-rhel9
        tag: latest
      csi-provisioner:
        digest: sha256:7ec0903a94f2dae3f5461077b73701eba94c38736e6dfce6013f6e79842ebe80
        image: ose-csi-external-provisioner-rhel9
        tag: latest
      csi-resizer:
        digest: sha256:c18ad7b81cbd0b6a3b8232a5249ab0e02876b0da7e07016258eade53763ee498
        image: ose-csi-external-resizer-rhel9
        tag: latest
      csi-snapshotter:
        digest: sha256:b1a2e7ac850f2ad135b90b8b1f44267d194bd8d9668c281cd6ee7282321e5f93
        image: ose-csi-external-snapshotter-rhel9
        tag: latest
  0_sig_storage_images.yaml: |
    base: registry.k8s.io/sig-storage
    components:
      csi-external-health-monitor-controller:
        digest: sha256:25925b16d02f21949a5ac55f8c120e81acdf204fe3d1a1ae1ae3653392bd56ba
        image: csi-external-health-monitor-controller
        tag: v0.17.0
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: linbit-sds
  name: linstor-operator-image-config
