---
catalog_templates:
  - template_name: v4.16.yaml
    channels: [stable]
    replaces: minio-minkms-operator.v2026.2.9031243
  - template_name: v4.17.yaml
    channels: [stable]
    replaces: minio-minkms-operator.v2026.2.9031243
  - template_name: v4.18.yaml
    channels: [stable]
    replaces: minio-minkms-operator.v2026.2.9031243
  - template_name: v4.19.yaml
    channels: [stable]
    replaces: minio-minkms-operator.v2026.2.9031243
  - template_name: v4.20.yaml
    channels: [stable]
    replaces: minio-minkms-operator.v2026.2.9031243
  - template_name: v4.21.yaml
    channels: [stable]
    replaces: minio-minkms-operator.v2026.2.9031243
