apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: replicated-rolebinding
  labels:
    app.kubernetes.io/name: replicated
    app.kubernetes.io/managed-by: olm
subjects:
- kind: ServiceAccount
  name: replicated
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: replicated-role
