apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: upgrade-webhook-service
    app.kubernetes.io/name: service
  name: upgrade-webhook-service
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/name: metax-operator
