---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: kubearmor-operator-manage-relay-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - list
  - watch
