apiVersion: v1
kind: ServiceAccount
metadata:
  name: iax-operator-sa
  labels:
    app.kubernetes.io/name: iax-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: olm
