apiVersion: v1
kind: ServiceAccount
metadata:
  name: iax-troubleshoot
  labels:
    app.kubernetes.io/name: iax-troubleshoot
    app.kubernetes.io/component: support
    app.kubernetes.io/managed-by: olm
