apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: trino-operator
    app.kubernetes.io/name: trino-operator
    app.kubernetes.io/version: 26.3.0
    stackable.tech/vendor: Stackable
  name: trino-operator
spec:
  ports:
  - name: conversion-webhook
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/instance: trino-operator
    app.kubernetes.io/name: trino-operator
    stackable.tech/vendor: Stackable
    webhook.stackable.tech/conversion: enabled
