apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: trino-operator
    app.kubernetes.io/name: trino-operator
    app.kubernetes.io/version: 26.3.0
    stackable.tech/vendor: Stackable
  name: trino-operator-clusterrole
rules:
- apiGroups:
  - opa.stackable.tech
  resources:
  - regorules
  verbs:
  - create
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes/proxy
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - pods
  - configmaps
  - secrets
  - services
  - endpoints
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - patch
  - list
  - watch
- apiGroups:
  - listeners.stackable.tech
  resources:
  - listeners
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - delete
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - trino.stackable.tech
  resources:
  - trinoclusters
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - trino.stackable.tech
  resources:
  - trinoclusters/status
  verbs:
  - patch
- apiGroups:
  - s3.stackable.tech
  resources:
  - s3connections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trino.stackable.tech
  resources:
  - trinocatalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.stackable.tech
  resources:
  - authenticationclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - trino-clusterrole
  resources:
  - clusterroles
  verbs:
  - bind
