apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: seawise-operator
  name: seawise-operator-seawise-viewer-role
rules:
- apiGroups:
  - backup.seawise.cloud
  resources:
  - seawises
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.seawise.cloud
  resources:
  - seawises/status
  verbs:
  - get
