{
 "title": "Airlock Microgateway Downstream - Metrics",
 "description": "Metrics on downstream traffic from/to clients.",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "gateway_kind",
    "label": "Gateway Kind",
    "query": {
     "query": "label_values(microgateway_build_info,gateway_kind)"
    }
   },
   {
    "name": "operator",
    "label": "Microgateway Operator",
    "query": {
     "query": "label_values(microgateway_build_info,managed_by)"
    }
   },
   {
    "name": "namespace",
    "label": "Gateway Namespace",
    "query": {
     "query": "label_values(microgateway_build_info{managed_by=~\"$operator\"},namespace)"
    }
   },
   {
    "name": "gateway_name",
    "label": "Gateway Name",
    "query": {
     "query": "label_values(microgateway_build_info{managed_by=~\"$operator\", namespace=~\"$namespace\", gateway_kind=~\"$gateway_kind\"},gateway)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Downstream Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Total number of downstream requests processed by Airlock Microgateway.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[$__range]))",
     "legendFormat": "Total Requests"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "stat",
   "description": "Percentage of 4xx and 5xx downstream requests. This includes requests blocked by Airlock Microgateway.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(envoy_http_downstream_rq_xx{envoy_response_code_class=~\"[45]\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[$__range]))/\nsum (increase(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[$__range]))",
     "legendFormat": "Request Error Rate"
    }
   ]
  },
  {
   "title": "1xx Requests",
   "type": "stat",
   "description": "Number of downstream requests with a 1xx response code processed by Airlock Microgateway.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"1\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[$__range]))",
     "legendFormat": "Total 1xx Requests"
    }
   ]
  },
  {
   "title": "2xx Requests",
   "type": "stat",
   "description": "Number of downstream requests with a 2xx response code processed by Airlock Microgateway.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"2\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[$__range]))",
     "legendFormat": "Total 2xx Requests"
    }
   ]
  },
  {
   "title": "3xx Requests",
   "type": "stat",
   "description": "Number of downstream requests with a 3xx response code processed by Airlock Microgateway.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"3\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[$__range]))",
     "legendFormat": "Total 3xx Requests"
    }
   ]
  },
  {
   "title": "4xx Requests",
   "type": "stat",
   "description": "Number of downstream requests with a 4xx response code processed by Airlock Microgateway.\nThis includes requests blocked by Airlock Microgateway.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"4\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[$__range]))",
     "legendFormat": "Total 4xx Requests"
    }
   ]
  },
  {
   "title": "5xx Requests",
   "type": "stat",
   "description": "Number of downstream requests with a 5xx response code processed by Airlock Microgateway.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[$__range]))",
     "legendFormat": "Total 5xx Requests"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Total downstream requests per second processed by Airlock Microgateway along with the observed error rate. The error rate includes requests blocked by Airlock Microgateway.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m]))",
     "legendFormat": "Requests per second"
    },
    {
     "expr": "sum (rate(envoy_http_downstream_rq_xx{envoy_response_code_class=~\"[45]\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m]) or on() vector(0))/\nsum (rate(envoy_http_downstream_rq_total{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m]))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "description": "Percentiles of the application downstream latency over one minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m])) by (le))",
     "legendFormat": "25th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "1xx Requests",
   "type": "timeseries",
   "description": "Downstream requests per second with a 1xx response code.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"1\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m]))",
     "legendFormat": "1xx Requests per second"
    }
   ]
  },
  {
   "title": "3xx Requests",
   "type": "timeseries",
   "description": "Downstream requests per second with a 3xx response code.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"3\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m]))",
     "legendFormat": "3xx Requests per second"
    }
   ]
  },
  {
   "title": "2xx Requests",
   "type": "timeseries",
   "description": "Downstream requests per second with a 2xx response code.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"2\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m]))",
     "legendFormat": "2xx Requests per second"
    }
   ]
  },
  {
   "title": "4xx Requests",
   "type": "timeseries",
   "description": "Downstream requests per second with a 4xx response code.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"4\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m]))",
     "legendFormat": "4xx Requests per second"
    }
   ]
  },
  {
   "title": "5xx Requests",
   "type": "timeseries",
   "description": "Downstream requests per second with a 5xx response code.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\", envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m]))",
     "legendFormat": "5xx Requests per second"
    }
   ]
  },
  { "title": "Downstream Connection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Connections",
   "type": "stat",
   "description": "Number of connections from downstream clients.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[$__range]))",
     "legendFormat": "Total Connections"
    }
   ]
  },
  {
   "title": "Data received",
   "type": "stat",
   "description": "Total amount of data received by Airlock Microgateway from downstream clients.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[$__range]))",
     "legendFormat": "Data received"
    }
   ]
  },
  {
   "title": "Data sent",
   "type": "stat",
   "description": "Total amount of data sent to downstream clients.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[$__range]))",
     "legendFormat": "Data sent"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Connections per second from downstream clients.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m]))",
     "legendFormat": "Connections per second"
    }
   ]
  },
  {
   "title": "Connection Length",
   "type": "timeseries",
   "description": "Histogram on the duration of connections from downstream clients.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum(rate(envoy_http_downstream_cx_length_ms_bucket{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m])) by (le))",
     "legendFormat": "25th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_cx_length_ms_bucket{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m])) by (le))",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_cx_length_ms_bucket{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Data received",
   "type": "timeseries",
   "description": "Rate of traffic received from downstream clients.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m]))",
     "legendFormat": "Data received"
    }
   ]
  },
  {
   "title": "Data sent",
   "type": "timeseries",
   "description": "Rate of traffic sent to downstream clients.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_tx_bytes_total{envoy_http_conn_manager_prefix=\"http\",managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway_kind=~\"${gateway_kind:regex}\", gateway=~\"${gateway_name:regex}\"}[1m]))",
     "legendFormat": "Data sent"
    }
   ]
  }
 ]
}