apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: directpv-operator
  name: directpv-operator-directpv-admin-role
rules:
- apiGroups:
  - charts.quay.io
  resources:
  - directpvs
  verbs:
  - '*'
- apiGroups:
  - charts.quay.io
  resources:
  - directpvs/status
  verbs:
  - get
