apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "charts.quay.io/v1alpha1",
          "kind": "Directpv",
          "metadata": {
            "name": "directpv-sample"
          },
          "spec": {
            "annotations": {},
            "controller": {
              "hostNetwork": false,
              "podAnnotations": {},
              "podLabels": {},
              "replicas": 3
            },
            "images": {
              "pullPolicy": "IfNotPresent",
              "pullSecrets": []
            },
            "labels": {},
            "license": "",
            "nodeserver": {
              "hostNetwork": false,
              "nodeSelector": {},
              "podAnnotations": {},
              "podLabels": {},
              "seccompLocalhostProfile": "",
              "tolerations": []
            }
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-04-09T17:04:40Z"
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "true"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.operatorframework.io/builder: operator-sdk-v1.42.0
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
    olm.skipRange: '>=5.0.7 <2026.4.9130438'
  name: minio-directpv.v2026.4.9130438
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: Directpv
        name: directpvs.charts.quay.io
        version: v1alpha1
  description: |
    DirectPV is a Kubernetes Container Storage Interface (CSI) driver designed for direct-attached storage. It enables container orchestrators to automatically manage the full lifecycle of local storage devices including discovery, formatting, mounting, scheduling, and monitoring across distributed environments. DirectPV is composed of two core components:

    • DirectPV CSI Driver – deployed within the Kubernetes cluster to provision and manage local persistent volumes.
    • DirectPV Plugin – a command-line utility installed on local machines to configure and interact with the CSI Driver.

    Unlike traditional SAN or NAS systems, DirectPV is not a storage backend but a distributed persistent-volume manager that exposes local disks directly to Kubernetes. This approach eliminates unnecessary data-path hops introduced by networked storage or SAN/NAS-based CSI drivers, delivering lower latency, higher throughput, and simplified storage management for modern distributed workloads.

    Distributed data platforms such as object storage, databases, and message queues benefit most from direct-attached storage, as they natively handle replication and data durability. Running these systems atop SAN/NAS-based CSI drivers introduces redundant replication layers and performance bottlenecks.

    For compatibility, prerequisites, release notes, and other user information, see [MinIO DirectPV documentation](https://min.io/docs/directpv/overview/).
  displayName: DirectPV
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAKcAAACnCAYAAAB0FkzsAAAACXBIWXMAABcRAAAXEQHKJvM/AAAIj0lEQVR4nO2dT6hVVRSHjykI/gMDU0swfKAi2KgGOkv6M1RpqI9qZBYo9EAHSaIopGCQA8tJDXzNgnRcGm+SgwLDIFR4omBmCQrqE4Tkxu/6Tlyv7569zzn73Lvu3t83VO+5HN/31t5r7bX3ntVqtVoZgD0mnuOHAlZBTjALcoJZkBPMgpxgFuQEsyAnmAU5wSzICWZBTjALcoJZkBPMgpxgFuQEsyAnmAU5wSzICWbRHqIJfjxgjiz77T8hbd197bqGkwAAAABJRU5ErkJggg==
      mediatype: image/png
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
            - apiGroups:
                - charts.quay.io
              resources:
                - directpvs
                - directpvs/status
                - directpvs/finalizers
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - services/finalizers
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - '*'
            - apiGroups:
                - storage.k8s.io
              resources:
                - csidrivers
                - storageclasses
              verbs:
                - '*'
            - apiGroups:
                - apiextensions.k8s.io
              resources:
                - customresourcedefinitions
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterrolebindings
                - clusterroles
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - serviceaccounts
              verbs:
                - '*'
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - rolebindings
                - roles
              verbs:
                - '*'
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: directpv-operator-controller-manager
      deployments:
        - label:
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/name: directpv-operator
            control-plane: controller-manager
          name: directpv-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                app.kubernetes.io/name: directpv-operator
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  app.kubernetes.io/name: directpv-operator
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --metrics-require-rbac
                      - --metrics-secure
                      - --metrics-bind-address=:8443
                      - --leader-elect
                      - --leader-election-id=directpv-operator
                      - --health-probe-bind-address=:8081
                    image: quay.io/minio/directpv-operator@sha256:1e4aa1b114bf7b99961431392b3b357de7aa4b6fa08906c03ebec29691e94856
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 1Gi
                      requests:
                        cpu: 100m
                        memory: 256Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                securityContext:
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
                serviceAccountName: directpv-operator-controller-manager
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: directpv-operator-controller-manager
    strategy: deployment
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - directpv
    - storage
    - csi
    - minio
  links:
    - name: DirectPV Operator
      url: https://min.io/docs/directpv/overview/
  maintainers:
    - email: dev@minio.io
      name: MinIO
  maturity: stable
  provider:
    name: MinIO, Inc
    url: https://min.io
  version: 2026.4.9130438
  relatedImages:
    - name: directpv-operator
      image: quay.io/minio/directpv-operator@sha256:1e4aa1b114bf7b99961431392b3b357de7aa4b6fa08906c03ebec29691e94856
