apiVersion: v1
data:
  0_linbit_sds_images.yaml: |
    base: drbd.io
    components:
      drbd-module-loader:
        digest: sha256:02b1ab37a9b8b40318d64f63fa7c08eb473cba552d786de7822d0a8fa3e39e42
        image: drbd9-rhel9
        match:
        - digest: sha256:f495f9b338397b64f65f4bd2e4cefc1e399615312796d37efcea188da5f37cb4
          image: drbd9-rhel7
          osImage: Red Hat Enterprise Linux Server 7\.
          precompiled: true
        - digest: sha256:b7808674768a6d1b278b8f92e3ca4978a18e1cc461d7446786ca1392f79b307f
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux 8\.
          precompiled: true
        - digest: sha256:02b1ab37a9b8b40318d64f63fa7c08eb473cba552d786de7822d0a8fa3e39e42
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux 9\.
          precompiled: true
        - digest: sha256:36ed46b065f6c0d47a5db4c0988abb77d172d9c09af9fdeda2a28729825c0469
          image: drbd9-rhel10
          osImage: Red Hat Enterprise Linux 10\.
          precompiled: true
        - digest: sha256:02b1ab37a9b8b40318d64f63fa7c08eb473cba552d786de7822d0a8fa3e39e42
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux CoreOS 9|(41[3-9])
          precompiled: true
        - digest: sha256:b7808674768a6d1b278b8f92e3ca4978a18e1cc461d7446786ca1392f79b307f
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux CoreOS
          precompiled: true
        - digest: sha256:f495f9b338397b64f65f4bd2e4cefc1e399615312796d37efcea188da5f37cb4
          image: drbd9-rhel7
          osImage: CentOS Linux 7
          precompiled: true
        - digest: sha256:b7808674768a6d1b278b8f92e3ca4978a18e1cc461d7446786ca1392f79b307f
          image: drbd9-rhel8
          osImage: CentOS Linux 8
          precompiled: true
        - digest: sha256:b7808674768a6d1b278b8f92e3ca4978a18e1cc461d7446786ca1392f79b307f
          image: drbd9-rhel8
          osImage: AlmaLinux 8
          precompiled: true
        - digest: sha256:02b1ab37a9b8b40318d64f63fa7c08eb473cba552d786de7822d0a8fa3e39e42
          image: drbd9-rhel9
          osImage: AlmaLinux 9
          precompiled: true
        - digest: sha256:36ed46b065f6c0d47a5db4c0988abb77d172d9c09af9fdeda2a28729825c0469
          image: drbd9-rhel10
          osImage: AlmaLinux 10
          precompiled: true
        - digest: sha256:b7808674768a6d1b278b8f92e3ca4978a18e1cc461d7446786ca1392f79b307f
          image: drbd9-rhel8
          osImage: Oracle Linux Server 8\.
          precompiled: true
        - digest: sha256:02b1ab37a9b8b40318d64f63fa7c08eb473cba552d786de7822d0a8fa3e39e42
          image: drbd9-rhel9
          osImage: Oracle Linux Server 9\.
          precompiled: true
        - digest: sha256:36ed46b065f6c0d47a5db4c0988abb77d172d9c09af9fdeda2a28729825c0469
          image: drbd9-rhel10
          osImage: Oracle Linux Server 10\.
          precompiled: true
        - digest: sha256:b7808674768a6d1b278b8f92e3ca4978a18e1cc461d7446786ca1392f79b307f
          image: drbd9-rhel8
          osImage: Rocky Linux 8
          precompiled: true
        - digest: sha256:02b1ab37a9b8b40318d64f63fa7c08eb473cba552d786de7822d0a8fa3e39e42
          image: drbd9-rhel9
          osImage: Rocky Linux 9
          precompiled: true
        - digest: sha256:36ed46b065f6c0d47a5db4c0988abb77d172d9c09af9fdeda2a28729825c0469
          image: drbd9-rhel10
          osImage: Rocky Linux 10
          precompiled: true
        tag: v9.2.19
      drbd-reactor:
        digest: sha256:f9459826dd517744f2177f7d85e3325ce97a5806e9ac3e48916ec759ee4056b6
        image: drbd-reactor
        tag: v1.11.0
      drbd-shutdown-guard:
        digest: sha256:16793f5aa10b46b198806c9198216fbd1aaec31269c28adea7e526dd17ff6f57
        image: drbd-shutdown-guard
        tag: v1.1.2
      ha-controller:
        digest: sha256:6373cac061702973b5460f742678adeb81167e23d774b0c1151252f2893b1c85
        image: linstor-k8s-ha-controller
        tag: v1.3.3
      ktls-utils:
        digest: sha256:3351a6e0fc048fe1544499095cdb8fdd221e832cecfa8a9a01f046c271991138
        image: ktls-utils
        tag: v1.2.1
      linstor-affinity-controller:
        digest: sha256:79b2e6b2afe8f1580ca68dbf58bd6185558ae96ffcf22fb15aadf19dad7b23aa
        image: linstor-affinity-controller
        tag: v1.4.2
      linstor-controller:
        digest: sha256:1dd44e9d18df31204a83b8cb141f2eedc93f5a506352186377200e56d6c216d9
        image: linstor-controller
        tag: v1.33.3
      linstor-csi:
        digest: sha256:526e9fed6d8563caa764b47e0f4f37027627481efead854c89ba628282589d79
        image: linstor-csi
        tag: v1.11.3
      linstor-satellite:
        digest: sha256:341cfe2c83e50a0d29c12a5e111260a7bb4152a86a09b91aad7c9164f96a6a50
        image: linstor-satellite
        tag: v1.33.3
      nfs-server:
        digest: sha256:647cd2bf7931b9652815a1652e9dc94788fbb9d7e3d283e0cd30ce9acaaf834b
        image: nfs-server
        tag: v1.11.3
  0_redhat_ose_images.yaml: |
    base: registry.redhat.io/openshift4
    components:
      csi-attacher:
        digest: sha256:db02739b53ae0af27b90424924fb4e403021154bf4425be0f4ffeb689d73bbf6
        image: ose-csi-external-attacher-rhel9
        tag: latest
      csi-livenessprobe:
        digest: sha256:b083249a3963559ae50d137ea929f1529bc4a1104de9b0553b541ffc63862957
        image: ose-csi-livenessprobe-rhel9
        tag: latest
      csi-node-driver-registrar:
        digest: sha256:2258a4abd2d704d08d6f94e674c4d7d90e28da89be61ff1be75d50b77fb73f6a
        image: ose-csi-node-driver-registrar-rhel9
        tag: latest
      csi-provisioner:
        digest: sha256:974a3f8aa688c646b4f88d61436afc8fc184221c79fadf1392b0ea1b63d56248
        image: ose-csi-external-provisioner-rhel9
        tag: latest
      csi-resizer:
        digest: sha256:56eb6d65c6631d587239e5813a9056a957a5b6df89b761908b925b3d8d4a05c7
        image: ose-csi-external-resizer-rhel9
        tag: latest
      csi-snapshotter:
        digest: sha256:059b9b65cc97477480c95439fc8783cd7b530f64d7aad04e93c24163dc130702
        image: ose-csi-external-snapshotter-rhel9
        tag: latest
  0_sig_storage_images.yaml: |
    base: registry.k8s.io/sig-storage
    components:
      csi-external-health-monitor-controller:
        digest: sha256:430c1f2267152ce6e4547ebbad225a2b399d03e5894f2f39ba233a38e4750a47
        image: csi-external-health-monitor-controller
        tag: v0.18.0
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: linbit-sds
  name: linstor-operator-image-config
