apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lightbits-operator
  name: lightbits-operator-storage-csidriver-editor-role
rules:
- apiGroups:
  - storage.lightbitslabs.com
  resources:
  - csidrivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.lightbitslabs.com
  resources:
  - csidrivers/status
  verbs:
  - get
