apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lightbits-operator
  name: lightbits-operator-storage-cluster-admin-role
rules:
- apiGroups:
  - storage.lightbitslabs.com
  resources:
  - clusters
  verbs:
  - '*'
- apiGroups:
  - storage.lightbitslabs.com
  resources:
  - clusters/status
  verbs:
  - get
