apiVersion: v1
data:
  minkms: |
    image: "quay.io/minio/aistor/minkms:RELEASE.2026-06-24T10-30-16Z"
  minkms-sidecar: |
    image: "quay.io/minio/aistor/minkms-sidecar:RELEASE.2026-07-14T22-12-08Z"
kind: ConfigMap
metadata:
  name: minkms-operator-default
