apiVersion: v1
data:
  API_SERVER_LOAD_BALANCER_ID: ""
  AUTOSCALER_CPUS: "2"
  AUTOSCALER_DEFINED_TAGS_NAMESPACE: ""
  AUTOSCALER_MAX_NODES: "3"
  AUTOSCALER_MEMORY: "4"
  AUTOSCALER_MIN_NODES: "1"
  AUTOSCALER_SHAPE: VM.Standard.E5.Flex
  BARE_METAL_SUBNET_ID: ""
  BARE_METAL_SUBNET_NAME: ""
  CAPI_VERSION: v1.12.3
  CAPOCI_VERSION: v0.24.0
  CLUSTER_NETWORK_CIDR_BLOCK: ""
  COMPARTMENT_ID: ""
  COMPUTE_NSG_NAME: ComputeNSG
  CONTROL_PLANE_ENDPOINT: ""
  IMAGE_ID: ""
  NETWORK_SECURITY_GROUP_ID: ""
  OCI_REGION: us-ashburn-1
  OCI_TENANCY_ID: ""
  OCI_USE_INSTANCE_PRINCIPAL: "true"
  OCI_USER_ID: ""
  OCP_SUBNET_ID: ""
  OCP_SUBNET_NAME: private
  SERVICE_NETWORK_CIDR_BLOCK: ""
  VCN_ID: ""
kind: ConfigMap
metadata:
  name: oci-capi-operator-config
