apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: opa-operator
    app.kubernetes.io/name: opa-operator
    app.kubernetes.io/version: 26.3.0
    stackable.tech/vendor: Stackable
  name: opa-operator-clusterrole
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes/proxy
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - pods
  - configmaps
  - secrets
  - services
  - endpoints
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - patch
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - opa.stackable.tech
  resources:
  - opaclusters
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - opa.stackable.tech
  resources:
  - opaclusters/status
  verbs:
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - opa-clusterrole
  resources:
  - clusterroles
  verbs:
  - bind
