apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "Device",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "device-sample"
          },
          "spec": {
            "clusterName": "sample-cluster"
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "Lvol",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "lvol-sample"
          },
          "spec": {
            "clusterName": "sample-cluster",
            "poolName": "pool-1"
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "Pool",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "pool-sample"
          },
          "spec": {
            "clusterName": "sample-cluster",
            "name": "pool-1"
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "SnapshotReplication",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "snapshotreplication-sample"
          },
          "spec": {
            "sourceCluster": "source-cluster",
            "targetCluster": "target-cluster",
            "targetPool": "target-pool"
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "StorageBackup",
          "metadata": {
            "name": "storagebackup-sample"
          },
          "spec": {
            "clusterName": "my-cluster",
            "pvcRef": {
              "name": "my-pvc"
            }
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "StorageCluster",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "storagecluster-sample"
          },
          "spec": {
            "backup": {
              "credentialsSecretRef": {
                "name": "sample-cluster-backup"
              },
              "localEndpoint": "http://10.10.11.10:9000",
              "localTesting": true,
              "secondaryTarget": 0,
              "snapshotBackups": true,
              "withCompression": false
            },
            "clusterName": "sample-cluster"
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "StorageNode",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "storagenode-sample"
          },
          "spec": {
            "clusterImage": "simplyblock/snode:latest",
            "clusterName": "sample-cluster",
            "maxLogicalVolumeCount": 256,
            "workerNodes": [
              "worker-node-1"
            ]
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "Task",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "task-sample"
          },
          "spec": {
            "clusterName": "sample-cluster"
          }
        }
      ]
    capabilities: Basic Install
    containerImage: quay.io/simplyblock-io/simplyblock-operator@sha256:b7db1d324fa1d6d272f40d696a46c11147de541ca54eb95e67760bc821dec4d8
    createdAt: "2026-05-01T09:35:35Z"
    operators.operatorframework.io/builder: operator-sdk-v1.42.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: simplyblock-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - description: Device is the Schema for the devices API
        displayName: Device
        kind: Device
        name: devices.storage.simplyblock.io
        version: v1alpha1
      - description: Lvol is the Schema for the lvols API
        displayName: Lvol
        kind: Lvol
        name: lvols.storage.simplyblock.io
        version: v1alpha1
      - description: Pool is the Schema for the pools API
        displayName: Pool
        kind: Pool
        name: pools.storage.simplyblock.io
        version: v1alpha1
      - description: SnapshotReplication is the Schema for the snapshotreplications API
        displayName: Snapshot Replication
        kind: SnapshotReplication
        name: snapshotreplications.storage.simplyblock.io
        version: v1alpha1
      - description: StorageBackup is the Schema for the storagebackups API.
        displayName: Storage Backup
        kind: StorageBackup
        name: storagebackups.storage.simplyblock.io
        version: v1alpha1
      - description: StorageCluster is the Schema for the storageclusters API
        displayName: Storage Cluster
        kind: StorageCluster
        name: storageclusters.storage.simplyblock.io
        version: v1alpha1
      - description: StorageNode is the Schema for the storagenodes API
        displayName: Storage Node
        kind: StorageNode
        name: storagenodes.storage.simplyblock.io
        version: v1alpha1
      - description: Task is the Schema for the tasks API
        displayName: Task
        kind: Task
        name: tasks.storage.simplyblock.io
        version: v1alpha1
  description: The Simplyblock Operator helps with installation, operation, and management of Simplyblock Control Planes, Storage Planes, and the CSI Driver.
  displayName: Simplyblock Operator
  icon:
    - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI4LjIuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCAzMDAgMzAwIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCAzMDAgMzAwOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+CjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+Cgkuc3Qwe2ZpbGw6IzI3NzZFQTt9CglAbWVkaWEgKHByZWZlcnMtY29sb3Itc2NoZW1lOiBkYXJrKSB7CgkJLnN0MHtmaWxsOiNGRkZGRkY7fQoJfQo8L3N0eWxlPgo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNMjQyLjQxLDEzMS42M2gtNTEuMjZsLTIwLjY4LDM1LjgyaDUxLjI2bC0zMS4wMiw1My43M0g4Ny41OUw2Ni45LDI1N2gxNDQuNDhsNTEuNy04OS41NUwyNDIuNDEsMTMxLjYzegoJIE0xMzQuMjksMjEyLjE5bDcyLjM0LTEyNS4zaC00MS4zNmwtNzIuMzQsMTI1LjNIMTM0LjI5eiBNMTY1LjI4LDEzMS42M2wtMjAuNjgsMzUuODJoLTEwLjM4bDIwLjY4LTM1LjgySDE2NS4yOHogTTEyOS4wOSwxMzEuNjMKCUg3Ni45NmwzMS4wMi01My43M2gxMDMuOWwyMC42OS0zNS44Mkg4Ny4zbC01MS43LDg5LjU1bDIwLjY4LDM1LjgyaDUyLjEzTDEyOS4wOSwxMzEuNjN6Ii8+Cjwvc3ZnPgo=
      mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
            - apiGroups:
                - ""
              resources:
                - nodes
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - ""
              resources:
                - persistentvolumeclaims
                - persistentvolumes
              verbs:
                - create
                - get
                - list
                - watch
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - secrets
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - discovery.k8s.io
              resources:
                - endpointslices
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - storage.k8s.io
              resources:
                - storageclasses
              verbs:
                - create
                - delete
                - get
                - list
                - watch
            - apiGroups:
                - storage.simplyblock.io
              resources:
                - backuprestores
                - devices
                - lvols
                - pools
                - snapshotreplications
                - storagebackups
                - storageclusters
                - storagenodes
                - tasks
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - storage.simplyblock.io
              resources:
                - backuprestores/finalizers
                - devices/finalizers
                - lvols/finalizers
                - pools/finalizers
                - snapshotreplications/finalizers
                - storagebackups/finalizers
                - storageclusters/finalizers
                - storagenodes/finalizers
                - tasks/finalizers
              verbs:
                - update
            - apiGroups:
                - storage.simplyblock.io
              resources:
                - backuprestores/status
                - devices/status
                - lvols/status
                - pools/status
                - snapshotreplications/status
                - storagebackups/status
                - storageclusters/status
                - storagenodes/status
                - tasks/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - apps
              resources:
                - daemonsets
              verbs:
                - create
                - delete
                - patch
                - update
                - watch
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - clusterrolebindings
                - clusterroles
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: simplyblock-operator-controller-manager
      deployments:
        - label:
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/name: simplyblock-operator
            control-plane: controller-manager
          name: simplyblock-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                app.kubernetes.io/name: simplyblock-operator
                control-plane: controller-manager
            strategy: {}
            template:
              metadata:
                annotations:
                  kubectl.kubernetes.io/default-container: manager
                labels:
                  app.kubernetes.io/name: simplyblock-operator
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - --metrics-bind-address=:8443
                      - --leader-elect
                      - --health-probe-bind-address=:8081
                    command:
                      - /manager
                    image: quay.io/simplyblock-io/simplyblock-operator@sha256:b7db1d324fa1d6d272f40d696a46c11147de541ca54eb95e67760bc821dec4d8
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    name: manager
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    resources:
                      limits:
                        cpu: 500m
                        memory: 128Mi
                      requests:
                        cpu: 10m
                        memory: 64Mi
                    securityContext:
                      allowPrivilegeEscalation: false
                      capabilities:
                        drop:
                          - ALL
                      readOnlyRootFilesystem: true
                securityContext:
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
                serviceAccountName: simplyblock-operator-controller-manager
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - coordination.k8s.io
              resources:
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ""
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: simplyblock-operator-controller-manager
    strategy: deployment
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - simplyblock
    - storage
    - nvme
    - nvme-tcp
    - nvme-rdma
    - software-defined storage
    - openshift
    - hyper-converged
    - disaggregated
  links:
    - name: Simplyblock Operator
      url: https://github.com/simplyblock/simplyblock-operator
    - name: Simplyblock Documentation
      url: https://docs.simplyblock.io
  maintainers:
    - email: info@simplyblock.io
      name: Simplyblock
  maturity: alpha
  minKubeVersion: 1.28.0
  provider:
    name: Simplyblock GmbH
    url: https://simplyblock.io/
  version: 0.1.0
  relatedImages:
    - name: simplyblock-operator
      image: quay.io/simplyblock-io/simplyblock-operator@sha256:b7db1d324fa1d6d272f40d696a46c11147de541ca54eb95e67760bc821dec4d8
    - name: simplyblock
      image: quay.io/simplyblock-io/simplyblock:26.2.1-PRE@sha256:adb13b6cd3bc7fbe2500c68c4107145c5da1120dcdb79884ba693d43d9ebaaab
    - name: ultra-spdk
      image: quay.io/simplyblock-io/ultra:R26.2-PRE-latest@sha256:f10a5b1186da852abe7e4dae6110a75554c46a51de229174acaec99dff283eb0
