---
catalog_templates:
  - template_name: v4.20.yaml
    channels: ['1.24']
    replaces: habana-ai-operator.v1.24.1-482
  - template_name: v4.20.yaml
    channels: [stable]
    replaces: habana-ai-operator.v1.24.1-482
  - template_name: v4.21.yaml
    channels: ['1.24']
    replaces: habana-ai-operator.v1.24.1-482
  - template_name: v4.21.yaml
    channels: [stable]
    replaces: habana-ai-operator.v1.24.1-482
  - template_name: v4.22.yaml
    channels: ['1.24']
    replaces: habana-ai-operator.v1.24.1-482
  - template_name: v4.22.yaml
    channels: [stable]
    replaces: habana-ai-operator.v1.24.1-482
  - template_name: v5.0.yaml
    channels: ['1.24']
  - template_name: v5.0.yaml
    channels: [stable]