apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: tawon
  name: tawon-operator-eob-eob-viewer
rules:
- apiGroups:
  - tawon.mantisnet.com
  resources:
  - directives
  - clusterdirectives
  - streamstores
  - streams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
