apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: hbase-operator
    app.kubernetes.io/name: hbase-operator
    app.kubernetes.io/version: 26.3.0
    stackable.tech/vendor: Stackable
  name: hbase-operator-clusterrole
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes/proxy
  verbs:
  - get
- apiGroups:
  - ''
  resources:
  - pods
  - configmaps
  - services
  - endpoints
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - create
  - delete
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - create
  - patch
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - listeners.stackable.tech
  resources:
  - listeners
  verbs:
  - get
- apiGroups:
  - hbase.stackable.tech
  resources:
  - hbaseclusters
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - hbase.stackable.tech
  resources:
  - hbaseclusters/status
  verbs:
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - hbase-clusterrole
  resources:
  - clusterroles
  verbs:
  - bind
