---
catalog_templates:
  - template_name: basic_template.yaml
    channels: [5.3.x]
    replaces: k8s-triliovault-stable.5.3.0
    skips:
    - k8s-triliovault-stable.5.0.0
    - k8s-triliovault-stable.5.0.1
    - k8s-triliovault-stable.5.0.2
    - k8s-triliovault-stable.5.0.3
    - k8s-triliovault-stable.5.0.4
    - k8s-triliovault-stable.5.1.0
    - k8s-triliovault-stable.5.1.1
    - k8s-triliovault-stable.5.1.2
    - k8s-triliovault-stable.5.2.0
    
