---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    healthProbeBindAddress: :8081
    metricsBindAddress: 127.0.0.1:8080
    leaderElection:
      enabled: true
      resourceID: network.amd.com
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: amd-network
    app.kubernetes.io/name: amd-network
    app.kubernetes.io/part-of: amd-network
  name: amd-network-operator-manager-config
