---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amd-network-operator-device-plugin-config
  labels:
    app.kubernetes.io/component: amd-network
    app.kubernetes.io/part-of: amd-network
data:
  # The config.json content for the SR-IOV device plugin
  config.json: |
    {
      "resourceList": [{
        "resourceName": "nic",
        "resourcePrefix": "amd.com",
        "enableExporterHealthCheck": true,
        "selectors": {
          "vendors": ["1dd8"],
          "devices": ["1002"],
          "drivers": ["ionic"],
          "isRdma": true
        },
        "excludeTopology": false
      },
      {
        "resourceName": "vnic",
        "resourcePrefix": "amd.com",
        "enableExporterHealthCheck": true,
        "selectors": {
          "vendors": ["1dd8"],
          "devices": ["1003"],
          "drivers": ["ionic"],
          "isRdma": true
        },
        "excludeTopology": false
      }]
    }
