apiVersion: v1
data:
  0_linbit_sds_images.yaml: |
    base: drbd.io
    components:
      drbd-module-loader:
        digest: sha256:d165bea95dc0e1df932d718658b5eadfefc7c11c92da54f3076b07e88ce4c5cc
        image: drbd9-rhel9
        match:
        - digest: sha256:4fa2f8bd8138262bfacec18ac9e53cb7588da7672263d7f202ce2a01e623e2b8
          image: drbd9-rhel7
          osImage: Red Hat Enterprise Linux Server 7\.
          precompiled: true
        - digest: sha256:3c0078f5953f25c656dd2c06a7df521c6fb15aa05f620b7d531ca344ca8b4df9
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux 8\.
          precompiled: true
        - digest: sha256:d165bea95dc0e1df932d718658b5eadfefc7c11c92da54f3076b07e88ce4c5cc
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux 9\.
          precompiled: true
        - digest: sha256:dd817192879261b3a83474877b22c62c380e34b609168d8907a9fdf53582c22b
          image: drbd9-rhel10
          osImage: Red Hat Enterprise Linux 10\.
          precompiled: true
        - digest: sha256:d165bea95dc0e1df932d718658b5eadfefc7c11c92da54f3076b07e88ce4c5cc
          image: drbd9-rhel9
          osImage: Red Hat Enterprise Linux CoreOS 9|(41[3-9])
          precompiled: true
        - digest: sha256:3c0078f5953f25c656dd2c06a7df521c6fb15aa05f620b7d531ca344ca8b4df9
          image: drbd9-rhel8
          osImage: Red Hat Enterprise Linux CoreOS
          precompiled: true
        - digest: sha256:4fa2f8bd8138262bfacec18ac9e53cb7588da7672263d7f202ce2a01e623e2b8
          image: drbd9-rhel7
          osImage: CentOS Linux 7
          precompiled: true
        - digest: sha256:3c0078f5953f25c656dd2c06a7df521c6fb15aa05f620b7d531ca344ca8b4df9
          image: drbd9-rhel8
          osImage: CentOS Linux 8
          precompiled: true
        - digest: sha256:3c0078f5953f25c656dd2c06a7df521c6fb15aa05f620b7d531ca344ca8b4df9
          image: drbd9-rhel8
          osImage: AlmaLinux 8
          precompiled: true
        - digest: sha256:d165bea95dc0e1df932d718658b5eadfefc7c11c92da54f3076b07e88ce4c5cc
          image: drbd9-rhel9
          osImage: AlmaLinux 9
          precompiled: true
        - digest: sha256:dd817192879261b3a83474877b22c62c380e34b609168d8907a9fdf53582c22b
          image: drbd9-rhel10
          osImage: AlmaLinux 10
          precompiled: true
        - digest: sha256:3c0078f5953f25c656dd2c06a7df521c6fb15aa05f620b7d531ca344ca8b4df9
          image: drbd9-rhel8
          osImage: Oracle Linux Server 8\.
          precompiled: true
        - digest: sha256:d165bea95dc0e1df932d718658b5eadfefc7c11c92da54f3076b07e88ce4c5cc
          image: drbd9-rhel9
          osImage: Oracle Linux Server 9\.
          precompiled: true
        - digest: sha256:dd817192879261b3a83474877b22c62c380e34b609168d8907a9fdf53582c22b
          image: drbd9-rhel10
          osImage: Oracle Linux Server 10\.
          precompiled: true
        - digest: sha256:3c0078f5953f25c656dd2c06a7df521c6fb15aa05f620b7d531ca344ca8b4df9
          image: drbd9-rhel8
          osImage: Rocky Linux 8
          precompiled: true
        - digest: sha256:d165bea95dc0e1df932d718658b5eadfefc7c11c92da54f3076b07e88ce4c5cc
          image: drbd9-rhel9
          osImage: Rocky Linux 9
          precompiled: true
        - digest: sha256:dd817192879261b3a83474877b22c62c380e34b609168d8907a9fdf53582c22b
          image: drbd9-rhel10
          osImage: Rocky Linux 10
          precompiled: true
        tag: v9.2.17
      drbd-reactor:
        digest: sha256:f9459826dd517744f2177f7d85e3325ce97a5806e9ac3e48916ec759ee4056b6
        image: drbd-reactor
        tag: v1.11.0
      drbd-shutdown-guard:
        digest: sha256:16793f5aa10b46b198806c9198216fbd1aaec31269c28adea7e526dd17ff6f57
        image: drbd-shutdown-guard
        tag: v1.1.2
      ha-controller:
        digest: sha256:13bc9273fe4b752aaa9a0aa0add2c4261589f80fae2d367ab36728b8abc93d0e
        image: linstor-k8s-ha-controller
        tag: v1.3.2
      ktls-utils:
        digest: sha256:3351a6e0fc048fe1544499095cdb8fdd221e832cecfa8a9a01f046c271991138
        image: ktls-utils
        tag: v1.2.1
      linstor-affinity-controller:
        digest: sha256:de3445f5bcc643e1b9d7c4e880fd289ca05dee300120d3b0d7a83498de91a79f
        image: linstor-affinity-controller
        tag: v1.3.0
      linstor-controller:
        digest: sha256:e2abff7690155fc8abbe1246b6166e9d65e51a544ac4709e4b01c43928306ca4
        image: linstor-controller
        tag: v1.33.1
      linstor-csi:
        digest: sha256:4d448a8c219c81407d3fe95b37bb8849aac6c4fe5b924b2a7ed6280228d4583a
        image: linstor-csi
        tag: v1.10.6
      linstor-satellite:
        digest: sha256:255bf22aadb0183b591fb8c098eaa8bf5eb722983bd3e02ed7393890942c12f2
        image: linstor-satellite
        tag: v1.33.1
      nfs-server:
        digest: sha256:8d76e28de2aed750f99149a82a2e356fa22fc19f497b369890e835cbdfbb83ae
        image: nfs-server
        tag: v1.10.6
  0_redhat_ose_images.yaml: |
    base: registry.redhat.io/openshift4
    components:
      csi-attacher:
        digest: sha256:4b6eebd491da07ea04b197edf6b54fce9fe8c4460e917c8ffd33436d2749a4d5
        image: ose-csi-external-attacher-rhel9
        tag: latest
      csi-livenessprobe:
        digest: sha256:fadd21095ba14bd0d033a74eacbd06f7e40a03b9acbaa846a85a5dc16d73ca00
        image: ose-csi-livenessprobe-rhel9
        tag: latest
      csi-node-driver-registrar:
        digest: sha256:188e4e2d697e2ca3c7c16772c0ab12253f00bd8433d8691ed7058fe7bafbbbf4
        image: ose-csi-node-driver-registrar-rhel9
        tag: latest
      csi-provisioner:
        digest: sha256:6bd78069858f772336af6d468caa38dd542a4fb2dbb44eda1551a76566de7c08
        image: ose-csi-external-provisioner-rhel9
        tag: latest
      csi-resizer:
        digest: sha256:8b7503084e43e8904d46dfe8216d6c4cb16ad92ac8faf83c515bfac914f1d483
        image: ose-csi-external-resizer-rhel9
        tag: latest
      csi-snapshotter:
        digest: sha256:3edbf250a8d585d688cf5ee15a1a4daf28273096c530c53325b71871b84b4982
        image: ose-csi-external-snapshotter-rhel9
        tag: latest
  0_sig_storage_images.yaml: |
    base: registry.k8s.io/sig-storage
    components:
      csi-external-health-monitor-controller:
        digest: sha256:25925b16d02f21949a5ac55f8c120e81acdf204fe3d1a1ae1ae3653392bd56ba
        image: csi-external-health-monitor-controller
        tag: v0.17.0
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: linbit-sds
  name: linstor-operator-image-config
