---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Seamless Upgrades
    category: All
    containerImage: quay.io/ciscointersightteam/intersight-operator@sha256:9d68fedd158ca0e3c5a18aa418b3570b53688f7cb43477f7b9d608e6906e260c
    console.openshift.io/plugins: '["intersight-plugin"]'
    createdAt: "2026-04-28T16:09:44Z"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/requires-cluster-admin: "false"
    features.operators.openshift.io/sdg-provider: "false"
    features.operators.openshift.io/supports-namespaces: "true"
    features.operators.openshift.io/supports-subscriptions: "true"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    olm.operatorGroup: cisco-intersight
    olm.operatorNamespace: cisco-intersight
    olm.targetNamespaces: cisco-intersight
    operatorframework.io/initialization-resource: |-
      {
        "apiVersion": "intersight.cisco.com/v1",
        "kind": "CiscoIntersight",
        "metadata": {
          "name": "intersight-resource",
          "namespace": "cisco-intersight",
          "labels": {
            "os.discoverytool.install": "intersight"
          }
        },
        "spec": {
          "OsDiscoveryToolInstall": false
        }
      }
    operatorframework.io/suggested-namespace: cisco-intersight
    operators.operatorframework.io.bundle.package.v1: cisco-intersight
    operators.operatorframework.io/builder: operator-sdk-v1.41.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
    support: Cisco Systems, Inc
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/os.linux: supported
  name: cisco-intersight.v1.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Cisco Intersight installs a dynamic plugin to display UCS hardware
        inventory and health in the cluster. The Console Plugin must be enabled for
        this custom resource to function.
      displayName: Cisco Intersight
      kind: CiscoIntersight
      name: ciscointersightapps.intersight.cisco.com
      version: v1
  description: "The Cisco Intersight Plugin for OpenShift integrates powerful hardware
    management directly into the OpenShift Web Console, bridging the gap between your
    applications and the physical servers they run on. \nIt provides OpenShift administrators
    with a unified view of server inventory, health status, real-time metrics, and
    security advisories. \nFrom within the OpenShift UI, you can perform critical
    operations like server power control, launch a vKVM session for deep troubleshooting,
    and initiate firmware upgrades. \nThis integration enables proactive management,
    allowing you to prevent outages by responding to hardware alerts before they impact
    production.\nPreRequisites \n- Outbound network connectivity to Intersight SaaS
    endpoints (us-east-1.intersight.com or eu-central-1.intersight.com). \n- Active
    Cisco Intersight account with server administrator access. \n- Cisco UCS servers
    registered in Intersight with Advantage License Tier or higher subscription.\n\nThe
    following images are deployed as part of the Operator and must be mirrored for
    use in a disconnected OpenShift environment.\n\n
    quay.io/ciscointersightteam/intersight-api@sha256:3ce4ac878512a262667b49594e72bdc06574dface1792548610136929883cf9e\n
    quay.io/ciscointersightteam/ucsinfra@sha256:accc922db0e38d0bd8272ab9bc9df104a3a28e6d0c60ac516dba61e03a06a9ac\n
    quay.io/ciscointersightteam/cisco-intersight-ui@sha256:79f5829dfe905e942fb294f1d4af40bca5be3374cc3a072623361e60aea8d474\n
    quay.io/ciscointersightteam/intersight-operator@sha256:9d68fedd158ca0e3c5a18aa418b3570b53688f7cb43477f7b9d608e6906e260c\n
    quay.io/ciscointersightteam/rhelucstool@sha256:ca6846163af12b4ae641c247f5bb3c614e6d1b6116e26d98885f908478a86ec5\n\n
    For more details, please refer to the documentation at https://intersight.com/help/saas/resources/plugin_openshift.\n
    Please contact Cisco TAC for any assistance."
  displayName: Cisco Intersight
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAOkAAAChCAYAAAAiPJjiAAAACXBIWXMAABcRAAAXEQHKJvM/AAAJ0ElEQVR4nO3dzXHbyBaG4W9uTRWWl7PDbuAAUJYjMBWBpQhERWArAkkRyBOBmIHoCERHYLoYgDE7LnmX3N1FH1oQBTYAEsTv+1RN1Rgg0U0IBz/dB90SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFTgj6Yr0EVBGI8kPUq6sEWJpJvNajlrrFItEoRxJLd/xrZoIel6s1oumqpTlxGkBwjC+FkvB2DaBw5EKQjjH5LOdhav5fZPUn+Nuu0/TVega4IwPlN2gErSVY1VaaUgjMd6G6CSNNLLnQdKIEjLG3nWZR2ceOHbd9iDIAVajiAFWo4gBVqOIAVajiAFWo4gBVqOIAVajiAFWu7PpitQtyCMLyR9tn8mku6bTFULwviLpE/2z4XVZ91gfSZ6yZxqtD6WI/1F0kdb9F3S1yb3TxMGFaRBGN9Jut1ZfBGEcSM5pUEYP0qapBaNJY2DMD5v4kAMwvhBLihaUR9JT3qdgjmWC9jzBurSmKHd7n7OWDbS28A9OcsBnmSs2rf8pOzNlS8Zq5qqz4Wyc6THtm4wBhOklvi9L3c0qq8mv/nyWJvIcY08697XVYkUXx70oHKkBxOkOMq/TVdgyAhSoOUIUqDlCFKg5QhSoOU600+6k4SwlutkH/x4Qls7SQiJGk7SaBNLinjQSwv2981qeddYhUrqRJDaAfi4s3jbyT74QM1IQpAaTNJooWe97rYZB2H8frNaXjZVoTK6crv7kLGskSSEtkmlzu0aKTt5Y1DsBJ/Vr3phCSWt15Ug3de5z8BWdPrniTzrOrF/uhKkwCkkTVegCIIUaDmCFGg5ghRoOYIUaDmCFGg5ghRoua4E6b6hO8oM6eHLTEpKbKcqvrqX+V3JgeuOKbMOvr/XvMR2Es+6tv3mTF0J0n9KLn/Dxuj5eux2qmLpjPOMVWtJ0xLbSZT9u9aS7uuuT1VsQuasSZlnm9VyXmI7U2UH/LQrKaWdCFJLhr7Xy1lxIemyzB/LtnOTsZ0m838v5QJge0afWX1KneFTv2v7vbltJzmgPl8z6lN2O5Ww3Nobud8zl5tN/ZB82/Od7VxvVsvrSipZA2b6LsnGSnres3q+WS0HNZLdrpz9c9+lt0/aohNXUmDICFKg5QjSaiVNVwD9Q5CWZI1V+xp2vtdYlbZaaP/+mdZYj94gSA9zrrcH4tSa+wfNWqbP9fquYi3XGp9kfQd+tO4eyEZEuJB7qXjWlT63OtnIB6OyXWUAAAAAAAAAAAAAAABoMTKOzDY7ZvvvoWfJWEZVehqGNVlVzRhskAZhHMlNaDSWf06QuVzS+Le8wLVtRntWL8qOuGDbPJNLP3yvt3PfrCX9lMuTnR+bG2uTG32S2yf75tlJ5PbHz2Ne4E6lVX6U2/+7f4OF/fddLu2yE+MRncLggtQC6VbSpORXc0cVCML4Tvtnejsvc3W2EQ5u5QKmkM1qedDf04LzVv7JjSopLzUL3GcVn3BrLTcO1dchBuug3oKxg/GHygdorWy+0WeVCNADyxkFYfwsN/drdMqyrLwLSb/kTghlZsTbTnP5y7YxKIMJ0iCMH+UOxlZPl2j1zJpvtOpyzlTDiSBV3kTSk47b/yNJT7atwRhEkNpt6KThauSyq8SkhnJGciesWubn3DNT+zEehxSovQ/S1LNdF9RVzyfVF6BnqjZAtx7tb9t7fzZdgRqUOUASvYwosNsFcVLWoOUrbybXePWqG8SC4EyuVbZIOROVu8Wdp/7/VTdVQU8lP1/GYxDGH/remNTrIA3C+IuKNYhMJf2TEQDbboIrSf+tun47Is+6xb5Boa3OCxUfP6jI1XotN5j0m66PVJfQVRDGI1+A2AkhyikrkRvY+3dZqf2e1+IcyT2/3+WU0Wm9DlK5Zn6ftdxo5lnTGWzH65lKmtqV7pR8V6goLyCKsGfeKOdj21H9M8tKnRTuLJh88k4IU7lR6V+Vtd3vQRjPJD3I/5z+WT0P0t4+k9oZP8r52N4A3VXDIFq+ABxJ+lFBY0neLbE3QHflXEXz9v9ss1pe+7axWS3XNh3E3LOdUd+7ZXobpMp/7poWDdCa5AVGJPcM9isI4wcLgrLyDmZv0FRY1lpSmblY8j5bW9tBE/ocpO9z1tc+k5qP3UYmBT4ayT2H/bCAvSuyfbs19d2eVj3i4UfPummZk4HdxfhOqL6yOq/PQRp51iUtTRa/Kfn5SNJtEMY/Cjwf5l1tqh7Y21efQ8oa7MDjfQ5Sn6TpCmSx2+/pAV89k/RcIFB9qj5p+U4Kh9xSt/GkWouhBmlrn2GsoeRG5Q/kM7mW0EONj/huHVqdznlKfQ7SxLNudGDDSy02q+VXSR/0eoLhIiaerqK8K1HeM3xZvvIO2fe9fu706XOQ/sxZn9eH2qjNapnYVfWd3AzcMxUL2Mme7a1zvn9RcV+wr6yrA7Y38azr9a1wn4N0nrN+0oXcT+srnG1Wy8vNavmXXHeELwB8V5y8Lqcqc2x9DT1nlg1WiLVg+253807IndbbIC3YpfHU5tveLDZz26HdR99y1o/tVbkq5J0Qbovs+9QL6ceU1Wm9DVJzn7N+JNcqujfFLQjjcRDGj0X7I2tyUMKBtR4nOR+bWJfOOGulvSg+CcL4V05ZeSfJbRZV5r4PwjhKvQPs0/uhVXqdu7tZLadBGOclaW/f+v8chPFC7jbtb/tO+q2PvIA/ij0PXsiNVbT3GavAq3dJTlE3yn8zZdulk8g9Nvwr17AUqVyjz73yg+xW7qo6l3u23L59VLScViWlnEKvg9Rcy41AkGck1w0xPmVlPCJZF0oQxtLLjNkLSf+TO3EUOXi9t7Sb1XJmietF8l0jHfESup0kr1Rsn44Lfi5tOoRRHXsfpJvVch6E8bVO8+LxKW2DcVziO0nBfORrlb8qHupablypqvs5E5XP0Oqkvj+TSvrd2FImoburCv1Ge4Y7Vw1dF5Z3e64Dn6P3WEu67Puz6NYgglT6HaiXqvZgaZPrMrd+qUCdnqpCqbIWqi5QE7nX6XrdN5o2mCCVfrduvlMNB2aNFpI+2EmolNT7mie/qlpQvdNx3SUzud86mACVBvBMusuuINdBGN/INYp8kn/snrncAXzqvrhtI1GR58S1XH2+VfFOrF2BP1jL8XYE+331SPQysnzZctaSLq2cKxVvlJrJDW8zL1tmHwxuBHufbVpcDaMwFKlHtGd1Umf9gjAenyo4rH90LHdC2M2UWshlEh09fQYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADq8X+nvy8fm8JzkgAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          - metrics.k8s.io
          resources:
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        - apiGroups:
          - config.openshift.io
          resources:
          - clusterversions
          - infrastructures
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - console.openshift.io
          resources:
          - consoleplugins
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - intersight.cisco.com
          resources:
          - ciscointersightapps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - intersight.cisco.com
          resources:
          - ciscointersightapps/finalizers
          verbs:
          - update
        - apiGroups:
          - intersight.cisco.com
          resources:
          - ciscointersightapps/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          - rolebindings
          - roles
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: cisco-intersight-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: ciscointersight-consoleoperator
          control-plane: controller-manager
        name: cisco-intersight-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: ciscointersight-consoleoperator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: ciscointersight-consoleoperator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: quay.io/ciscointersightteam/intersight-operator@sha256:9d68fedd158ca0e3c5a18aa418b3570b53688f7cb43477f7b9d608e6906e260c
                imagePullPolicy: IfNotPresent
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 500m
                    memory: 128Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: cisco-intersight-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - resourcequotas
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - pods
          - secrets
          - serviceaccounts
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps/finalizers
          - secrets/finalizers
          verbs:
          - update
        - apiGroups:
          - intersight.cisco.com
          resources:
          - ciscointersightapps/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: cisco-intersight-controller-manager
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - Cisco
  - Intersight
  - ConsolePlugin
  - UCS
  links:
  - name: Intersight Consoleoperator
    url: https://intersight.com/help/saas
  maintainers:
  - email: TEAM_300359@cisco.com
    name: Intersight
  maturity: stable
  minKubeVersion: 1.16.0
  provider:
    name: Cisco Intersight
    url: https://intersight.com/help/saas
  relatedImages:
    - image: quay.io/ciscointersightteam/intersight-operator@sha256:9d68fedd158ca0e3c5a18aa418b3570b53688f7cb43477f7b9d608e6906e260c
      name: intersight-operator
    - image: quay.io/ciscointersightteam/intersight-api@sha256:3ce4ac878512a262667b49594e72bdc06574dface1792548610136929883cf9e
      name: intersight-api
    - image: quay.io/ciscointersightteam/ucsinfra@sha256:accc922db0e38d0bd8272ab9bc9df104a3a28e6d0c60ac516dba61e03a06a9ac
      name: intersight-node-discovery
    - image: quay.io/ciscointersightteam/rhelucstool@sha256:ca6846163af12b4ae641c247f5bb3c614e6d1b6116e26d98885f908478a86ec5
      name: intersight-rhelucstool
    - image: quay.io/ciscointersightteam/cisco-intersight-ui@sha256:79f5829dfe905e942fb294f1d4af40bca5be3374cc3a072623361e60aea8d474
      name: intersight-consoleui-plugin
  version: 1.0.1