apiVersion: v1
data:
  CEPHCSI: |
    channel: stable-4.23
    csv: cephcsi-operator.v4.23.0-16.stable
    pkg: cephcsi-operator
    scaleUpOnInstanceOf:
      - operatorconfigs.csi.ceph.io
  CNSA: |
    channel: stable-v60.1
    csv: ibm-spectrum-scale-operator.v60.1.100
    pkg: ibm-spectrum-scale-operator
    namespace: ibm-spectrum-scale
    scaleUpOnInstanceOf:
      - clusters.scale.spectrum.ibm.com
  CNSA_DEPS: |
    channel: stable-4.23
    csv: cnsa-dependencies.v4.23.0-16.stable
    pkg: cnsa-dependencies
    namespace: ibm-spectrum-scale
  CSIADDONS: |
    channel: stable-4.23
    csv: odf-csi-addons-operator.v4.23.0-16.stable
    pkg: odf-csi-addons-operator
    scaleUpOnInstanceOf:
      - csiaddonsnodes.csiaddons.openshift.io
  IBM_CSI: |
    channel: stable-v1.13.2
    csv: ibm-block-csi-operator.v1.13.2
    pkg: ibm-block-csi-operator
    scaleUpOnInstanceOf:
      - flashsystemclusters.odf.ibm.com
  IBM_ODF: |
    channel: stable-v1.9
    csv: ibm-storage-odf-operator.v1.9.0
    pkg: ibm-storage-odf-operator
    scaleUpOnInstanceOf:
      - flashsystemclusters.odf.ibm.com
  NOOBAA: |
    channel: stable-4.23
    csv: mcg-operator.v4.23.0-16.stable
    pkg: mcg-operator
    scaleUpOnInstanceOf:
      - noobaas.noobaa.io
  OCS: |
    channel: stable-4.23
    csv: ocs-operator.v4.23.0-16.stable
    pkg: ocs-operator
    scaleUpOnInstanceOf:
      - storageclusters.ocs.openshift.io
  OCS_CLIENT: |
    channel: stable-4.23
    csv: ocs-client-operator.v4.23.0-16.stable
    pkg: ocs-client-operator
    scaleUpOnInstanceOf:
      - storageclients.ocs.openshift.io
      # In external mode, no storage client is present, but the client operator
      # is still required to create the CSI-related CRs.
      - cephclusters.ceph.rook.io
  OCS_TLS: |
    channel: stable-4.23
    csv: ocs-tls-profiles.v4.23.0-16.stable
    pkg: ocs-tls-profiles
  ODF_DEPS: |
    channel: stable-4.23
    csv: odf-dependencies.v4.23.0-16.stable
    pkg: odf-dependencies
  PROMETHEUS: |
    channel: stable-4.23
    csv: odf-prometheus-operator.v4.23.0-16.stable
    pkg: odf-prometheus-operator
    scaleUpOnInstanceOf:
      - alertmanagers.monitoring.coreos.com
      - prometheuses.monitoring.coreos.com
  RECIPE: |
    channel: stable-4.23
    csv: recipe.v4.23.0-16.stable
    pkg: recipe
  ROOK: |
    channel: stable-4.23
    csv: rook-ceph-operator.v4.23.0-16.stable
    pkg: rook-ceph-operator
    scaleUpOnInstanceOf:
      - cephclusters.ceph.rook.io
  SNAPSHOT_CONTROLLER: |
    channel: stable-4.23
    csv: odf-external-snapshotter-operator.v4.23.0-16.stable
    pkg: odf-external-snapshotter-operator
    scaleUpOnInstanceOf:
      - volumegroupsnapshotclasses.groupsnapshot.storage.openshift.io
kind: ConfigMap
metadata:
  name: odf-operator-pkgs-config-4.23.0-16.stable
