# Copyright (c) 2026 MetaX Integrated Circuits (Shanghai) Co., Ltd. All rights reserved.
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/name: service
  name: controller-manager-metrics-service
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: metax-operator
