apiVersion: v1
data:
  kes: |
    image: "quay.io/minio/aistor/kes:RELEASE.2026-08-24T11-11-49Z"
  kes-sidecar: |
    image: "quay.io/minio/aistor/kes-sidecar:RELEASE.2026-07-14T22-03-37Z"
  minio: |
    image: "quay.io/minio/aistor/minio:RELEASE.2026-09-07T08-39-31Z"
  minio-sidecar: |
    image: "quay.io/minio/aistor/minio-sidecar:RELEASE.2026-09-18T00-46-19Z"
  minwall: |
    image: "quay.io/minio/aistor/minwall:RELEASE.2026-05-21T06-25-56Z"
kind: ConfigMap
metadata:
  name: object-store-operator-default
