{
 "title": "Airlock Microgateway Threats Block - Metrics",
 "description": "Metrics on threats blocked by Airlock Microgateway.\n\nDashboard can be filtered by namespaces as well as block types.",
 "tags": [ "airlock-microgateway" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource Prometheus", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "DS_LOKI", "query": "loki" },
   {
    "name": "operator",
    "label": "Operator",
    "query": {
     "query": "label_values(microgateway_build_info,managed_by)"
    }
   },
   {
    "name": "namespace",
    "label": "Gateway Namespace",
    "query": {
     "query": "label_values(microgateway_build_info{managed_by=~\"$operator\"},namespace)"
    }
   },
   {
    "name": "gateway_name",
    "label": "Gateway Name",
    "query": {
     "query": "label_values(microgateway_build_info{managed_by=~\"$operator\", namespace=~\"$namespace\"},gateway)"
    }
   },
   {
    "name": "gateway_httproute",
    "label": "Gateway HTTPRoute",
    "query": {
     "query": "label_values(envoy_cluster_bind_errors{managed_by=~\"$operator\", namespace=~\"$namespace\", gateway=~\"$gateway_name\"},upstream)"
    }
   },
   {
    "name": "block_type",
    "label": "Block Type",
    "query": {
     "query": "label_values(microgateway_http_downstream_rq_threats_blocked_total,block_type)"
    }
   },
   {
    "name": "block_subtype",
    "label": "Block Subtype",
    "query": {
     "query": "label_values(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"$block_type\"},block_subtype)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Airlock Microgateway Threats Block - Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Requests",
   "type": "stat",
   "description": "Total number of requests processed by Airlock Microgateway.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\",namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range]))+\nsum(increase(microgateway_http_downstream_rq_threats_blocked_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range]) or on() vector(0)))",
     "legendFormat": "Processed Requests"
    }
   ]
  },
  {
   "title": "% Blocked Requests",
   "type": "stat",
   "description": "Ratio of blocked requests vs. processed requests by Airlock Microgateway.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${block_type:regex}\", block_subtype=~\"${block_subtype:regex}\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range]) or on() vector(0))\n/ \n(\nsum(increase(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range]))\n+\nsum(increase(microgateway_http_downstream_rq_threats_blocked_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range]) or on() vector(0))\n)",
     "legendFormat": "Blocked Requests (%)"
    }
   ]
  },
  {
   "title": "Requests vs. % Blocks",
   "type": "timeseries",
   "description": "Requests per second processed by Airlock Microgateway along with the corresponding block rate.",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))\n+\nsum(rate(microgateway_http_downstream_rq_threats_blocked_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]) or on() vector(0))",
     "legendFormat": "Requests per second"
    },
    {
     "expr": "sum(rate(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${block_type:regex}\", block_subtype=~\"${block_subtype:regex}\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]) or on() vector(0))\n/\n(\nsum(rate(envoy_cluster_upstream_rq{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]))\n+\nsum(rate(microgateway_http_downstream_rq_threats_blocked_total{managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[1m]) or on() vector(0))\n)",
     "legendFormat": "% Blocks"
    }
   ]
  },
  {
   "title": "Block Type",
   "type": "barchart",
   "description": "Blocked threats by block type.",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (block_type) (increase(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${block_type:regex}\", block_subtype=~\"${block_subtype:regex}\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Subtype",
   "type": "barchart",
   "description": "Blocked threats by block subtype, which are subsets of the various block types.",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (block_subtype) (increase(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${block_type:regex}\", block_subtype=~\"${block_subtype:regex}\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Affected Routes / Applications",
   "type": "barchart",
   "description": "Lists the top 10 routes / applications most affected by blocks, along with their associated gateway name.",
   "gridPos": { "h": 15, "w": 20, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_join(topk(10, round(sum by (gateway, upstream) (increase(microgateway_http_downstream_rq_threats_blocked_total{block_type=~\"${block_type:regex}\", block_subtype=~\"${block_subtype:regex}\", managed_by=~\"${operator:regex}\", namespace=~\"${namespace:regex}\", gateway=~\"${gateway_name:regex}\", envoy_cluster_name=~`^httproute/.+`,upstream=~`${gateway_httproute:regex}`}[$__range])))), 'gateway_upstream', '/', 'gateway', 'upstream')",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}