apiVersion: v1
data:
  mc: |
    image: "quay.io/minio/aistor/mc:RELEASE.2026-03-12T04-18-55Z"
kind: ConfigMap
metadata:
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-03-18T17-36-17Z
  name: adminjob-operator
