apiVersion: v1
data:
  kes: |
    image: "quay.io/minio/aistor/kes:RELEASE.2026-03-14T05-28-50Z"
  kes-sidecar: |
    image: "quay.io/minio/aistor/kes-sidecar:RELEASE.2026-03-18T11-55-01Z"
  minio: |
    image: "quay.io/minio/aistor/minio:RELEASE.2026-03-17T21-25-16Z"
  minio-sidecar: |
    image: "quay.io/minio/aistor/minio-sidecar:RELEASE.2026-03-18T17-20-10Z"
kind: ConfigMap
metadata:
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2026-03-18T17-36-17Z
  name: object-store-operator-default
