---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-operator-deployer-manifests
data:
  storageclass.yaml: |
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: secrets.stackable.tech
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        stackable.tech/vendor: Stackable
        app.kubernetes.io/version: 26.3.0
    provisioner: secrets.stackable.tech
  service.yaml: |
    apiVersion: v1
    kind: Service
    metadata:
      name: secret-operator
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        stackable.tech/vendor: Stackable
        app.kubernetes.io/version: 26.3.0
    spec:
      selector:
        webhook.stackable.tech/conversion: enabled
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        stackable.tech/vendor: Stackable
      ports:
      - name: conversion-webhook
        protocol: TCP
        port: 8443
        targetPort: 8443
  daemonset.yaml: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: secret-operator-csi-node-driver
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        stackable.tech/vendor: Stackable
        app.kubernetes.io/version: 26.3.0
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: secret-operator
          app.kubernetes.io/instance: secret-operator
          stackable.tech/vendor: Stackable
      template:
        metadata:
          annotations:
            internal.stackable.tech/image: quay.io/stackable/secret-operator@sha256:c2c72ecc057c548f72b040fde6d0c7a997938e757f1e6fec6f78dd2add444af1
          labels:
            app.kubernetes.io/name: secret-operator
            app.kubernetes.io/instance: secret-operator
            stackable.tech/vendor: Stackable
        spec:
          serviceAccountName: secret-operator-serviceaccount
          securityContext: {}
          containers:
          - name: csi-node-service
            securityContext:
              privileged: true
              runAsUser: 0
            image: quay.io/stackable/secret-operator@sha256:c2c72ecc057c548f72b040fde6d0c7a997938e757f1e6fec6f78dd2add444af1  # 26.3.0
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 256Mi
            args:
            - run
            - csi-node-service
            env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
            - name: PRIVILEGED
              value: 'true'
            - name: OPERATOR_IMAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['internal.stackable.tech/image']
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_SERVICE_NAME
              value: secret-operator
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            volumeMounts:
            - name: csi
              mountPath: /csi
            - name: mountpoint
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
            - name: tmp
              mountPath: /tmp
          - name: external-provisioner
            image: quay.io/stackable/sig-storage/csi-provisioner@sha256:142e0b069dcc100671c91d66d8c973d56ea330b4e11ab79e5eb4fea5c79c6ecb  # v5.3.0
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 128Mi
            args:
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
            - --extra-create-metadata
            volumeMounts:
            - name: csi
              mountPath: /csi
          - name: node-driver-registrar
            image: quay.io/stackable/sig-storage/csi-node-driver-registrar@sha256:ab4a3289015f7de39c4dc987fa6183bcb157294a841c88fa842332ce66b068d8  # v2.15.0
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 100m
                memory: 128Mi
            args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/secrets.stackable.tech/csi.sock
            volumeMounts:
            - name: registration-sock
              mountPath: /registration
            - name: csi
              mountPath: /csi
          volumes:
          - name: registration-sock
            hostPath:
              path: /var/lib/kubelet/plugins_registry
          - name: csi
            hostPath:
              path: /var/lib/kubelet/plugins/secrets.stackable.tech/
          - name: mountpoint
            hostPath:
              path: /var/lib/kubelet/pods/
          - name: tmp
            emptyDir: {}
  deployment.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: secret-operator
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        stackable.tech/vendor: Stackable
        app.kubernetes.io/version: 26.3.0
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: secret-operator
          app.kubernetes.io/instance: secret-operator
          stackable.tech/vendor: Stackable
      template:
        metadata:
          annotations:
            internal.stackable.tech/image: quay.io/stackable/secret-operator@sha256:c2c72ecc057c548f72b040fde6d0c7a997938e757f1e6fec6f78dd2add444af1
          labels:
            webhook.stackable.tech/conversion: enabled
            app.kubernetes.io/name: secret-operator
            app.kubernetes.io/instance: secret-operator
            stackable.tech/vendor: Stackable
        spec:
          serviceAccountName: secret-operator-serviceaccount
          securityContext: {}
          containers:
          - name: secret-operator
            securityContext:
              runAsUser: 0
            image: quay.io/stackable/secret-operator@sha256:c2c72ecc057c548f72b040fde6d0c7a997938e757f1e6fec6f78dd2add444af1  # 26.3.0
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: 100m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 256Mi
            args:
            - run
            - controller
            env:
            - name: OPERATOR_IMAGE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['internal.stackable.tech/image']
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_SERVICE_NAME
              value: secret-operator
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
  csidriver.yaml: |
    apiVersion: storage.k8s.io/v1
    kind: CSIDriver
    metadata:
      name: secrets.stackable.tech
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        stackable.tech/vendor: Stackable
        app.kubernetes.io/version: 26.3.0
    spec:
      attachRequired: false
      podInfoOnMount: true
      fsGroupPolicy: File
      volumeLifecycleModes:
      - Persistent
  stackable-secret-operator-scc.yaml: |
    apiVersion: security.openshift.io/v1
    kind: SecurityContextConstraints
    metadata:
      name: stackable-secret-operator-scc
      annotations:
        kubernetes.io/description: SCC for Stackable secret operator
    allowHostDirVolumePlugin: true
    allowHostIPC: false
    allowHostNetwork: false
    allowHostPID: false
    allowHostPorts: false
    allowPrivilegeEscalation: true
    allowPrivilegedContainer: true
    allowedCapabilities: null
    defaultAddCapabilities: null
    fsGroup:
      type: RunAsAny
    groups: []
    priority: null
    readOnlyRootFilesystem: false
    requiredDropCapabilities:
    - MKNOD
    runAsUser:
      type: RunAsAny
    seLinuxContext:
      type: MustRunAs
    supplementalGroups:
      type: RunAsAny
    users: []
    volumes:
    - downwardAPI
    - projected
    - hostPath
    - emptyDir
