on:
  issue_comment:
    types: [created]

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/re-trigger') }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      PR: ${{ github.event.issue.number }}
    steps:
      - name: Add temporary re-trigger label
        run: gh pr edit "$PR" --add-label pipeline/trigger

      - name: Comment a PR
        run: gh pr comment "$PR" --body 'The certification pipeline will be triggered soon.'

      - name: Remove a temporary label
        run: gh pr edit "$PR" --remove-label pipeline/trigger
