name: Github pull request labels

on:
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write

jobs:
  skip-test-labeler:
    uses: redhat-openshift-ecosystem/github-workflows/.github/workflows/label-command.yml@10ccef93d0efbbecf3bc9916512f6dcf5f0670c1  # main
