kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: fujitsu-enterprise-postgres
  name: fep-scc-clusterrole
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - fep-restrictedv2-scc
