apiVersion: v1
kind: Service
metadata:
  name: px-multi-cluster-operator-service
  labels:
    app.kubernetes.io/name: px-multi-cluster-operator
    app.kubernetes.io/component: manager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: px-multi-cluster-operator-tls
spec:
  type: ClusterIP
  ports:
  - name: rest
    port: 8710
    targetPort: rest
    protocol: TCP
  - name: grpc
    port: 7710
    targetPort: grpc
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  - name: health
    port: 9003
    targetPort: health
    protocol: TCP
  - name: webhook
    port: 443
    targetPort: 9443
    protocol: TCP
  selector:
    app.kubernetes.io/name: px-multi-cluster-operator
